wso2/carbon-dashboards

- apps/portal/js/create.js
This issue is due to URL text box is being updated for every key released to ensure the URL is within maximum of 100 characters. In that case, when a backspace/delete character or other common keys are pressed, the URL need not be updated as they will have no effect in increase of URL length. This PR fixes that issue.
Public JIra - [https://wso2.org/jira/browse/UES-900]
> [UES-900] Difficult to delete characters in the beginning of a URL in a dashboard

- apps/portal/configs/designer.json
- apps/portal/controllers/acs.jag
- apps/portal/controllers/apis/HTTPClient.jag
- apps/portal/controllers/apis/RESTClientInvoker.jag
- apps/portal/controllers/apis/XMLHTTPClient.jag
- apps/portal/controllers/constants/constants.js
- apps/portal/controllers/login.jag
- apps/portal/modules/dashboards.js
- apps/portal/modules/tokenUtil.js
- components/shindig-wso2-features/src/main/javascript/wso2features/features.txt
- components/shindig-wso2-features/src/main/javascript/wso2features/remoteClient/HttpRequest.js
- components/shindig-wso2-features/src/main/javascript/wso2features/remoteClient/XMLHttpRequest.js
- components/shindig-wso2-features/src/main/javascript/wso2features/remoteClient/feature.xml
If SSO is enabled, obtaining a token (OAuth2) using SAML Token and if SSO is disabled a token is generated (OAuth2) using password grant type. So when creating request from gadget level it will first redirected to remoteClient shindig feature. Afterwards, it will be redirected to either HTTPClient or XMLHTTPClient. This where an actual request is made to give backed REST service. If OAuth is enabled access token is being set in request header otherwise this part won't happen
> Adding feature to access the secured backend APIs at gadgets level

- components/shindig-server/pom.xml
- components/shindig-server/src/main/resources/features.txt
- pom.xml
This is to avoid start-up errors that can be caused by lack of internet connection. Removing the online features at carbon-dashboards level.
> Moving the fix of removing online features from product-ds to carbon-dashboards

- components/org.wso2.carbon.dashboards.metadata.api/pom.xml
- components/org.wso2.carbon.dashboards.metadata.api/src/main/java/org/wso2/carbon/dashboards/metadata/api/DataHolder.java
- components/org.wso2.carbon.dashboards.metadata.api/src/main/java/org/wso2/carbon/dashboards/metadata/api/MetadataProviderAPI.java
- components/org.wso2.carbon.dashboards.metadata/pom.xml
- components/org.wso2.carbon.dashboards.metadata/src/main/java/org/wso2/carbon/dashboards/metadata/internal/provider/impl/MetadataProviderImpl.java
- components/org.wso2.carbon.dashboards.view/pom.xml
- components/org.wso2.carbon.dashboards.view/src/main/component.yaml
- pom.xml
In this PR, the metadata provider backend service is registered as an OSGi and it is being consumed by the metadata provider API. Metadata provider API is an MSF4J service, a REST API, which is intended to be deployed at the application deployment.
The API currently supports add, delete, update and get for metadata. The implementation ATM is a pass through to the metadata provider backend, we may improve it as required.
> Metadata API for view component

- apps/portal/routers/tenant.jag
This will fix the 400 response when GLOBAL-STATE parameter is there in the query string.
> Fixing 400 bad request for URLs with GLOBAL-STATE

- components/org.wso2.carbon.dashboards.designer/src/main/fragments/dashboard-designer/public/js/designer.js
This PR resolves #530 i.e. Widget cannot be added to a newly added block in a page.
> Fix issue in add block function

- components/dashboards-web-component/src/DashboardListing.jsx
- components/dashboards-web-component/src/DashboardRenderingComponent.jsx
- components/dashboards-web-component/src/DashboardThumbnail.jsx
- components/dashboards-web-component/src/DashboardView.jsx
- components/dashboards-web-component/src/widget/Widget.jsx
This PR introduces widget state persistence when sharing dashboards (resolves https://github.com/wso2/carbon-dashboards/issues/566). In order to persist and retrieve the state of the widget a set of client-side APIs are exposed to widget using the `Widget` parent component. 
In order to use the widget capabilities provided by the dashboard, a widget needs to extend from `Widget` component.
```js
import React, { Component } from 'react';
import Widget from './Widget'
class SampleWidget extends Widget {
/* ... */
}
```
```js
/* ... */
class SampleWidget extends Widget {
/* ... */
setWidegtState() {
super.getDashboardAPI().state.set('level', 4);
}
/* ... */
}
```
```js
/* ... */
class SampleWidget extends Widget {
/* ... */
getWidgetState() {
let currentLevel = …
```
> Add Widget State Persistance

- components/dashboards/org.wso2.carbon.dashboards.core/pom.xml
- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/bean/DashboardConfigurations.java
- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/DataHolder.java
- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/ServiceComponent.java
- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/dao/utils/QueryManager.java
- features/org.wso2.carbon.dashboards.api.feature/src/main/resources/p2.inf
- pom.xml
This PR contains the Carbon Kernel migration to version 5.2.0-alpha.
This includes changes related to `carbon-configs` and  `carbon-datasources`, which requires configuration changes in the `deployment.yaml` file. Please add the following configurations into the `deployment.yaml` file.
```yaml
wso2.dashboard:
queries:
h2:
add_dashboard: INSERT INTO DASHBOARD_RESOURCE (DASHBOARD_URL, DASHBOARD_NAME, DASHBOARD_DESCRIPTION, DASHBOARD_PARENT_ID , DASHBOARD_LANDING_PAGE, DASHBOARD_CONTENT) VALUES (?, ?, ?, ?, ?, ?)
get_dashboard_by_url: SELECT DASHBOARD_ID, DASHBOARD_URL, DASHBOARD_NAME, DASHBOARD_DESCRIPTION, DASHBOARD_PARENT_ID, DASHBOARD_LANDING_PAGE, DASHBOARD_CONTENT FROM DASHBOARD_RESOURCE WHERE DASHBOARD_URL = ?
get_dashboard_metadata_list: SELECT DASHBOARD_ID, DASHBOARD_URL, …
```
> Carbon Kernel 5.2.0-alpha Migration

- components/dashboards-web-component/package.json
- components/dashboards-web-component/pom.xml
- components/dashboards-web-component/public/locales/en.json
- components/dashboards-web-component/public/locales/fr.json
- components/dashboards-web-component/src/App.jsx
- components/dashboards-web-component/src/designer/DashboardCreatePage.jsx
- components/dashboards/org.wso2.carbon.dashboards.api/pom.xml
- components/dashboards/org.wso2.carbon.dashboards.core/pom.xml
- features/org.wso2.carbon.dashboards.api.feature/pom.xml
- features/org.wso2.carbon.dashboards.portal.feature/pom.xml
- pom.xml
For dashboard app to be used outside the English-speaking world, we’ll have to adapt all our strings, dates, and numbers to the conventions of different locales.
This feature will enable localization support for the react app
A third party library called react-intl is used to get the localization support.
Locale files will be at HOME/deployment/reactapps/portal/public/locales/
Any new locale files can be added with the name of the locale either with the region code or not.
Ex: en.json, fr.json
en.json and fr.json files are added in the app for reference.
> Adding localization support with react-intl

- components/dashboards-web-component/pom.xml
- components/dashboards/org.wso2.carbon.dashboards.api/pom.xml
- components/dashboards/org.wso2.carbon.dashboards.core/pom.xml
- features/org.wso2.carbon.dashboards.api.feature/pom.xml
- features/org.wso2.carbon.dashboards.portal.feature/pom.xml
- pom.xml
Cannot build `carbon-dashboards` in Windows.
Fixes #614 
Ability to build `carbon-dashboards`d in Windows.
Added Maven profiles for different OSs (Windows & Unix) in the `pom.xml` of `dashboards-web-component`. Also added a default profile that will be activated if non-other is active.
- OS: Windows 7
- Node: v6.11.4
- NPM: 3.10.10
- Maven: v3.2.2
- Java: 1.8._112
- OS: Ubuntu 16.04
- Node: v6.11.4
- NPM: 3.10.10
- Maven: v3.2.2
- Java: 1.8._112
> Add Maven profiles for different OSs in web component's pom.xml

- components/dashboards-web-component/package.json
- components/dashboards-web-component/src/App.jsx
- components/dashboards-web-component/src/auth/Login.jsx
- components/dashboards-web-component/src/auth/Logout.jsx
- components/dashboards-web-component/src/auth/SecuredRouter.jsx
- components/dashboards-web-component/src/auth/utils/AuthManager.jsx
- components/dashboards-web-component/src/common/components/Header.jsx
- components/dashboards-web-component/src/utils/Constants.jsx
- components/dashboards-web-component/src/utils/apis/AuthenticationAPI.jsx
Dashboard component currently doesn't have an authentication mechanism. This PR introduces basic authentication support (i.e. login, logout and session management) in dashboard component.
Resolves https://github.com/wso2/carbon-dashboards/issues/653
This PR introduces login/logout pages which can be used to login to the portal app. Apart from that provides cookie based session management. 
This implementation uses the existing common authentication API in carbon-analytics-common.
- Confirmed that this PR doesn't commit any …
> Integrate authentication

- components/dashboards/org.wso2.carbon.dashboards.core/src/test/java/org/wso2/carbon/dashboards/core/internal/DashboardMetadataProviderImplTest.java
- components/dashboards/org.wso2.carbon.dashboards.core/src/test/java/org/wso2/carbon/dashboards/core/internal/database/DashboardMetadataDaoTest.java
- components/dashboards/org.wso2.carbon.dashboards.core/src/test/java/org/wso2/carbon/dashboards/core/internal/io/WidgetConfigurationReaderTest.java
Currently `org.wso2.carbon.dashboards.core` component lacks unit tests.
Add unit tests for `org.wso2.carbon.dashboards.core` component and improe code coverage.
Added unit tests for 
- DashboardMetadataDao
Code coverage for `org.wso2.carbon.dashboards.core` component is 75%
- Unit tests 
`org.wso2.carbon.dashboards.core`: 75%
N/A
#656
> Add more unit tests for org.wso2.carbon.dashboards.core component

- components/dashboards-web-component/src/designer/DashboardCreatePage.jsx
- components/dashboards-web-component/src/utils/Constants.jsx
Resolves https://github.com/wso2/carbon-dashboards/issues/665
Dashboard creation was failing due to wrong http status code used. Proper http status code ( 201 ) is used to fix the issue.
> Fix dashboard creation issue

- components/dashboards-web-component/src/designer/DashboardDesigner.css
- components/dashboards-web-component/src/designer/DashboardDesigner.jsx
- components/dashboards-web-component/src/utils/DashboardRenderingComponent.jsx
- samples/widgets/Publisher/src/Publisher.jsx
- samples/widgets/Publisher/src/Widget.jsx
- samples/widgets/Subscriber/src/Subscriber.jsx
- samples/widgets/Subscriber/src/Widget.jsx
> This PR introduces message queue implementation for publisher widgets. It resolves the message loss issue when the publisher widgets are loaded before subscriber widgets. Moreover this provides fixes for several bugs in carbon-dashboards alpha4 release.
> Fix several bugs and message loss issue in pubsub communication.
> There is an event loss if the publisher widget is rendered before the subscriber widget. Because publisher widgets start publishing and subscriber widgets are not ready to receive messages. So we have introduced a message queue in order to resolve this issue. We kept the messages in a queue until the dashboard is initialized. Once the dashboard is initialized, we flush all the messages in the message queue.
- Followed secure coding standards in …
> Add message queue support for publisher widgets

- components/dashboards-web-component/src/designer/components/PageEntry.jsx
- components/dashboards-web-component/src/designer/components/PagesPanel.jsx
- components/dashboards-web-component/src/listing/DashboardThumbnail.jsx
> This will fix the issue in dashboard listing page and marking landing page option. Let's consider a situation where there are multiple dashboards in the listing page and tries to delete one dashboard from it. Although we delete the dashboard, it is still showing on the listing page sometimes. If we change the landing page to a different page other than the home, it is not possible to change it back to Home page.
> Fix the issues reported in GIT
>  java version "1.8.0_131"
Java(TM) SE Runtime Environment (build …
> Fix issues in dashboard listing page and marking landing page option.

- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/io/WidgetConfigurationReader.java
- components/dashboards/org.wso2.carbon.dashboards.core/src/test/java/org/wso2/carbon/dashboards/core/internal/WidgetInfoProviderImplTest.java
- pom.xml
Bump carbon-ui-server to v0.12.0
> Bump carbon-ui-server to v0.12.0

- components/dashboards-web-component/src/designer/DashboardDesigner.jsx
- components/dashboards-web-component/src/utils/DashboardRenderingComponent.jsx
- components/dashboards-web-component/src/viewer/DashboardView.jsx
Resolves https://github.com/wso2/product-sp/issues/84
Pop out button config has been disabled globally from the dashboard config so that it will not be visible to any of the widgets. Also configuration buttons are enabled for the designer mode.
> Disable pop out button in designer and enabling configuration buttons in viewer

- components/dashboards-web-component/src/designer/DashboardDesigner.jsx
- components/dashboards-web-component/src/designer/components/WidgetsList.jsx
- components/dashboards-web-component/src/viewer/DashboardView.jsx
> This PR will use widgetID instead of widget name to render widgets. Moreover, this will remove the minimum width and height introduced in golden layout level.
> use widgetID instead of widget name to render widget
> remove the minimum width and height introduced in golden layout level
>  Use widgetId to render the widgets

- components/dashboards-web-component/public/css/dashboard.css
- components/dashboards-web-component/src/utils/DashboardRenderingComponent.jsx
- components/dashboards-web-component/src/viewer/DashboardView.jsx
This PR introduces a loading spinner in dashboard view page. The spinner will be displayed while the dashboard is loaded and renders at the background.
Relates to https://github.com/wso2/carbon-dashboards/issues/722
> Add loading spinner in dashboard view

- features/org.wso2.carbon.dashboards.portal.feature/src/main/resources/p2.inf
- samples/features/org.wso2.carbon.dashboards.samples.feature/src/main/resources/p2.inf
`Portal` app is currently resides under `<CARBON_HOME>/deployment` directory. But this needs to be moved into `<CARBON_HOME>/wso2/<RUNTIME>/deployment` directory. This PR introduces necessary changes in `p2.inf` files in order to copy the `portal` app and respective widgets into the latter directory. 
> Move portal app into runtime deployment directory

- components/dashboards-web-component/package.json
- components/dashboards-web-component/src/auth/SecuredRouter.jsx
Once the user login again after logout, `/portal` context is dropping from the URLs which redirects user to invalid URLs. This PR fixes that issue.
> Fix issue in referrer path

- samples/widgets/UniversalWidget/package.json
> Bumped React-VizGrammar version to v0.6.6 in UniversalWidget
NPM v5.3.0, Node.JS v8.5.0
> Bumped React-VizGrammar version to v0.6.6 in UniversalWidget

- components/dashboards/org.wso2.carbon.dashboards.api/pom.xml
- components/dashboards/org.wso2.carbon.dashboards.api/src/main/java/org/wso2/carbon/dashboards/api/internal/DashboardRestApi.java
- components/dashboards/org.wso2.carbon.dashboards.api/src/main/java/org/wso2/carbon/dashboards/api/internal/DashboardRestApiProvider.java
- components/dashboards/org.wso2.carbon.dashboards.api/src/main/java/org/wso2/carbon/dashboards/api/internal/WidgetRestApi.java
- components/dashboards/org.wso2.carbon.dashboards.core/pom.xml
- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/WidgetMetadataProvider.java
- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/WidgetMetadataProviderImpl.java
- components/dashboards/org.wso2.carbon.dashboards.core/src/test/java/org/wso2/carbon/dashboards/core/internal/WidgetMetadataProviderImplTest.java
- pom.xml
Bumps, 
- Carbon UI Server version to 0.17.0
- Analytics Common version to v6.0.36
- Analytics version to v2.0.197
> Bump Carbon UI Server version to 0.17.0

- components/dashboards-web-component/src/designer/DashboardCreatePage.jsx
- components/dashboards-web-component/src/designer/DashboardSettings.jsx
When user visits dashboard settings or create pages, click cancel and try again to visit those pages, empty page will be shown and the `/portal/` context is getting missed from the URL.
Resolves https://github.com/wso2/carbon-dashboards/issues/747
This issue happens because the user is redirected to `/portal` instead of `/portal/` URL. This PR fixes that issue.
> Fix issue in dashboard settings/create pages

- components/dashboards-web-component/src/auth/Login.jsx
This PR fixes the issue which shown blank error messages after failed login attempt in dashboard login page.
Resolves https://github.com/wso2/carbon-dashboards/issues/758
As a fix this changeset clears the React.js state which is used to show the error message after error message closes. This fixes the issue.
> Fix blank error message in login page

- components/dashboards-web-component/src/designer/components/WidgetsList.jsx
This PR hides the UniversalWidget from the widget list in dashboard designer.
Resolves https://github.com/wso2/carbon-dashboards/issues/743
> Hide universal widget from widget list

- components/dashboards-web-component/src/gadgets-generation-wizard/components/GadgetsGenerationWizard.jsx
- components/dashboards-web-component/src/gadgets-generation-wizard/components/chartPreview/PreviewerWidget.jsx
> Adding un-subscription to the channel manager when preview dialog is closed
> Adding unsubscribe widget on preview close

- samples/widgets/sales-dashboard-widgets/CustomersByProduct/package.json
- samples/widgets/sales-dashboard-widgets/CustomersPerYear/package.json
- samples/widgets/sales-dashboard-widgets/OverallProductInfo/package.json
- samples/widgets/sales-dashboard-widgets/OverallRevenueInfo/package.json
- samples/widgets/sales-dashboard-widgets/RevenueByCountry/package.json
- samples/widgets/sales-dashboard-widgets/RevenueByProduct/package.json
- samples/widgets/sales-dashboard-widgets/RevenueByRegion/package.json
- samples/widgets/sales-dashboard-widgets/RevenuePerYear/package.json
- samples/widgets/sales-dashboard-widgets/RevenuePercentage/package.json
This PR updates `react-vizgrammer` version to `0.6.9`.
> Update react-vizgrammer version to 0.6.9

- components/dashboards-web-component/public/locales/en.json
- components/dashboards-web-component/public/locales/fr.json
- components/dashboards-web-component/src/viewer/Dashboard.css
- components/dashboards-web-component/src/viewer/DashboardView.jsx
This PR introduces a **Home** button in dashboard viewer.
Resolves https://github.com/wso2/carbon-dashboards/issues/774
> Add home button in dashboard viewer

- samples/widgets/UniversalWidget/package.json
- samples/widgets/UniversalWidget/src/UniversalWidget.jsx
Removed renderWidget method from the UniversalWidget to fix the styling issues associated with the UniversalWidget
> Removed renderWidget method from the UniversalWidget

- samples/widgets/Subscriber/src/Subscriber.jsx
- samples/widgets/UserInfo/src/UserInfo.jsx
- samples/widgets/WidgetState/src/WidgetState.jsx
- samples/widgets/sales-dashboard-widgets/CustomersPerYear/src/CustomersPerYear.jsx
- samples/widgets/sales-dashboard-widgets/RevenueByCountry/src/RevenueByCountry.jsx
removing the renderWidget function from the sample widgets to remove it from the base-widget
> Removed renderWidget function from the sample widgets

- base-widget/src/Widget.jsx
Removed renderWidget function call from the base widget as it is no longer required.
> Removing renderWidget function from the render function of the base widget

- components/dashboards-web-component/src/gadgets-generation-wizard/components/chartPropertyGenerators/main/LineAreaBarChart.jsx
- components/dashboards-web-component/src/gadgets-generation-wizard/components/chartPropertyGenerators/main/PieChart.jsx
- components/dashboards-web-component/src/gadgets-generation-wizard/components/chartPropertyGenerators/main/ScatterChart.jsx
- components/dashboards-web-component/src/gadgets-generation-wizard/utils/Configurations.js
- components/dashboards-web-component/src/gadgets-generation-wizard/utils/UtilFunctions.js
> Adding `append` boolean option for some charts.
> Allowing the user to optionally select appending data from streaming providers
> Adding 'append' configuration for some chart types

- components/dashboards-web-component/src/auth/SecuredRouter.jsx
This PR reduces the interval which is used to check and refresh access tokens to 60 secs (which is less than timeout skew). 
If the checking interval is greater than the timeout skew, there can be situations which the logic misses possible token expiry.
> Reduce the token refreshing timeout to 60s.

- components/dashboards-web-component/src/designer/DashboardDesigner.jsx
By default, the widgets panel in dashboard designer is collapsed. This PR fixes that issue and makes the widgets panel open by default when the user visits the designer. This will provide a clue about the next operation user has to do with the designer, i.e. dragging and dropping a widget.
> Made widgets panel visible by default in designer

- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/bean/roles/provider/Roles.java
- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/DashboardMetadataProviderImpl.java
- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/roles/provider/RolesProvider.java
This PR refactors the dashboard creator role configuration in `deployment.yaml`. Earlier the dashboard creator configuration has been depicted as follows in the `deployment.yaml`.
```yaml
wso2.dashboard:
roles:
creators:
-
id: 1
name: role_1
-
id: 2
name: role_2
```
Since the role details are already there in the same configuration file, with this change only providing the role IDs will be sufficient. New `deployment.yaml` configuration looks as follows.
```yaml
wso2.dashboard:
roles:
creators: [1, 2]
```
In addition to that this PR fixes an issue in dashboard permissions, i.e. when a particular role has `owner` permission it does not allow to design the dashboard. Instead `owner` permission should have total access to that dashboard.
- Followed secure coding standards in …
> Refactoring dashboard creator role configuration

- pom.xml
- Bumps msf4j version to v2.5.2
- Bumps carbon analytics version to v2.0.246
- Bumps carbon analytics-common version to v6.0.51
> Bump msf4j, carbon analytics, carbon analytics-common versions

- components/dashboards-web-component/src/viewer/DashboardView.jsx
- components/dashboards-web-component/src/viewer/components/PageMenu.jsx
- components/dashboards-web-component/src/viewer/components/Sidebar.jsx
In dashboard viewer, page menu renders two entries for a single page (one of them is blank). This PR fixes that issue.
Resolves https://github.com/wso2/carbon-dashboards/issues/833
> Fix blank menu items in dashboard view page menu

- components/dashboards-web-component/src/designer/DashboardDesigner.css
- components/dashboards-web-component/src/designer/components/WidgetsList.jsx
> This will provide fixes for following issues,
#746 
#772 
#773 
Provide more smooth user experience for the dashboard designers.
This PR will introduce a calc method and calculate the designer view and widget configuration panel width according to window width. So it will not overlap different screen resolutions.
NA
NA
NA
NA
NA
NA
NA
NA
NA
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
Node - v8.8.1-linux-x64
Resolves #746 …
> Fix widget configuration panel overlap issue in designer

- samples/widgets/LoadAverage/src/recharts-style.css
This PR adds a missing style file in LoadAverage sample.
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
https://github.com/wso2/carbon-dashboards/pull/845
N/A
N/A
N/A
> Add missing style file

- components/dashboards-web-component/package.json
- components/dashboards-web-component/src/gadgets-generation-wizard/components/GadgetsGenerationWizard.jsx
- components/dashboards-web-component/src/gadgets-generation-wizard/components/ProviderConfigurator.jsx
- components/dashboards-web-component/src/gadgets-generation-wizard/components/inputTypes/CodeProperty.jsx
- components/dashboards-web-component/src/gadgets-generation-wizard/components/inputTypes/TextProperty.jsx
- components/dashboards-web-component/src/gadgets-generation-wizard/utils/Types.js
- components/dashboards-web-component/src/gadgets-generation-wizard/utils/UtilFunctions.js
> - Implementing render input fields based on the API response
> - Introducing `CodeProperty` for SQL & Siddhi query related fields
> - Rendering input fields based on given configuration types, rather than checking the values of them
> https://github.com/wso2/carbon-analytics/pull/1160
> Introducing field types for rendering data provider config fields

- components/dashboards-web-component/package-lock.json
- components/dashboards-web-component/package.json
- samples/widgets/CpuUsage/package-lock.json
- samples/widgets/LoadAverage/package-lock.json
- samples/widgets/MemoryUsage/package-lock.json
- samples/widgets/Publisher/package-lock.json
- samples/widgets/Subscriber/package-lock.json
- samples/widgets/TotalUpdates/package-lock.json
- samples/widgets/UniversalWidget/package-lock.json
- samples/widgets/UniversalWidget/package.json
- samples/widgets/UserInfo/package-lock.json
- samples/widgets/WidgetState/package-lock.json
- samples/widgets/sales-dashboard-widgets/CustomersByProduct/package-lock.json
- samples/widgets/sales-dashboard-widgets/CustomersByProduct/package.json
- samples/widgets/sales-dashboard-widgets/CustomersPerYear/package-lock.json
- samples/widgets/sales-dashboard-widgets/CustomersPerYear/package.json
- samples/widgets/sales-dashboard-widgets/OverallProductInfo/package-lock.json
- samples/widgets/sales-dashboard-widgets/OverallProductInfo/package.json
- samples/widgets/sales-dashboard-widgets/OverallRevenueInfo/package-lock.json
- samples/widgets/sales-dashboard-widgets/OverallRevenueInfo/package.json
- samples/widgets/sales-dashboard-widgets/RevenueByCountry/package-lock.json
- samples/widgets/sales-dashboard-widgets/RevenueByCountry/package.json
- samples/widgets/sales-dashboard-widgets/RevenueByProduct/package-lock.json
- samples/widgets/sales-dashboard-widgets/RevenueByProduct/package.json
- samples/widgets/sales-dashboard-widgets/RevenueByRegion/package.json
- samples/widgets/sales-dashboard-widgets/RevenuePerYear/package-lock.json
- samples/widgets/sales-dashboard-widgets/RevenuePerYear/package.json
- samples/widgets/sales-dashboard-widgets/RevenuePercentage/package-lock.json
- samples/widgets/sales-dashboard-widgets/RevenuePercentage/package.json
Upgrade react-Vizgrammer version to 0.6.18 for weekly release.
Upgrade react-Vizgrammer version to 0.6.18 for weekly release.
Upgrade react-Vizgrammer version to 0.6.18 for weekly release. Since there are some issues with the pie charts, these widgets are only upgraded into 0.6.17
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
> Upgrade react-Vizgrammer version to 0.6.18

- components/shindig-server/pom.xml
> There is a vulnerability CVE-2016-3092 in the apache-commons-fileupload.1.3.1.jar file. This is packed to carbon-dashboard via shindig server. We have removed that from this fix so that it will be taken from the fileupload jar in our plugins of the carbon-pack
> Fix the vulnerability issue.
> Remove the jar and zip it back
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
N/A
N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> Remove apache commons fileupload vulnerable jar from shindig

- components/dashboards-web-component/src/auth/Login.jsx
Set `autocomplete="off"` attribute to the username, password inputs in the login page.
> Fix auto complete issue in the login page

- pom.xml
- samples/features/org.wso2.carbon.dashboards.samples.feature/pom.xml
$subject, as `org.wso2.carbon.dashboards.samples.widgets.universal-widget` does not exists any more
> Remove org.wso2.carbon.dashboards.samples.widgets.universal-widget dependency

- components/dashboards-web-component/src/viewer/DashboardView.jsx
This PR fixes an issue in dashboard view page, which the hamburger button does not collapse the sidebar.
Resolves https://github.com/wso2/carbon-dashboards/issues/864
> Fix dashboard view un-collapsible sidebar

- components/dashboards-web-component/src/designer/components/WidgetConfigurationPane.jsx
> Fix the bug where widget configuration panel does not appear for widgets with different id and name property

- components/dashboards-web-component/src/gadgets-generation-wizard/components/chartPreview/PreviewerWidget.jsx
Fix for WidgetChannelManager not working in Preview Widget of Chart Generation Wizard
Node JS v8.8.1, NPM v5.4.2
> Fix for WidgetChannelManager not working in Preview Widget of Chart Generation Wizard

- components/dashboards-web-component/src/auth/Login.jsx
- components/dashboards-web-component/src/auth/Logout.jsx
In carbon-dashboards 4.0.17, following issues happen when a user tries to login after logout.
1. Login page refreshes when the use key-presses on username field for the first time.
2. After successful login, the user gets redirected to `http://localhost:9643/portal/portal` instead of the dashboard listing page.
Resolves https://github.com/wso2/carbon-dashboards/issues/922
> Fix faulty redirection on login

- components/universal-widget/src/UniversalWidget.jsx
This will enable the Universal Widget to change it's theme with the Dashboard Theme change.
Node.JS v8.8.1, NPM v5.4.2
> Add support for theme Dashboard theme change in Universal Widget

- base-widget/package-lock.json
- base-widget/package.json
- base-widget/src/Widget.jsx
Custom widgets the should be able to get the widget configurations 
Introduce getWidgetConfiguration API to get the widget configuration
The API will return httpClient.get function, which can then be used to access the widget configurations
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
> Adding getWidgetConfiguration API to base-widget

- components/dashboards-web-component/src/gadgets-generation-wizard/components/GadgetsGenerationWizard.jsx
> Remove unused step 'PubSub Configurations' in gadget-generation wizard UI

- samples/widgets/DateTimeRangePicker/src/DateRangePicker.jsx
This reverts commit 5c51b17ffb659c2bbc9c91a9a1e58658339c389b.
The above functionality ONLY works intermittently. For instance, If the subscriber widget loads later than the publisher, the initial published message is not reached and the state not updated.
> Revert "Publish default time range at first load"

- components/universal-widget/src/UniversalWidget.jsx
> Add box-sizing for UniversalWidget to add a gap between chart and container margin

- components/dashboards-web-component/src/designer/components/LeftSidePane.jsx
- components/dashboards-web-component/src/designer/components/PagesSidePane.jsx
- components/dashboards-web-component/src/designer/components/WidgetsSidePane.jsx
- components/dashboards-web-component/src/designer/components/dashboard-container-styles.css
- components/dashboards-web-component/src/viewer/DashboardViewPage.jsx
- components/dashboards-web-component/src/viewer/components/dashboard-container-styles.css
Fixes #974
Set `overflowY` to `auto` instead of `scroll`.
> Fix scroll bar always visible issue in Pages, Widgets panes in the designer

- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/roles/provider/RolesProvider.java
This PR fixes default `roleId` (for `admin` user) on creating a dashboard.
> Fix default roleId on creating dashboard

- components/dashboards-web-component/src/listing/components/DashboardCard.jsx
In Firefox, "more options" for dashboards in dashboard listing page does not appear. Hence it is not possible to access the designer, setting pages and delete a dashboard.
This PR fixes that issue.
> Fix listing page more options in Firefox

- components/dashboards-web-component/public/locales/en.json
- components/dashboards-web-component/public/locales/fr.json
- components/dashboards-web-component/src/designer/components/PageCard.jsx
- components/dashboards-web-component/src/designer/components/PagesSidePane.jsx
- components/dashboards-web-component/src/viewer/DashboardViewPage.jsx
This PR introduces an option in the dashboard designer pages panel to hide specific pages. 
Resolves https://github.com/wso2/carbon-dashboards/issues/983
> Introduce option to hide dashboard pages.

- components/dashboards-web-component/src/designer/components/DashboardRenderer.jsx
In the dashboard viewer, if a widget does not have styles defined the default theme will be applied. But in the dashboard designer, it is not. This PR applies default theme for widgets in the dashboard designer.
Resolves https://github.com/wso2/carbon-dashboards/issues/991
> Add default theme for widgets in designer

- components/dashboards-web-component/package.json
- components/dashboards-web-component/public/locales/en.json
- components/dashboards-web-component/public/locales/fr.json
- components/dashboards-web-component/src/designer/DashboardDesignerPage.jsx
- components/dashboards-web-component/src/designer/components/DashboardRenderer.jsx
- components/dashboards-web-component/src/designer/components/LeftSideActions.jsx
- components/dashboards-web-component/src/designer/components/PageCard.jsx
- components/dashboards-web-component/src/designer/components/PagesSidePane.jsx
- components/dashboards-web-component/src/designer/components/dashboard-container-styles.css
- components/dashboards-web-component/src/utils/GLResizable.css
- components/dashboards-web-component/src/viewer/DashboardViewPage.jsx
- components/dashboards-web-component/src/viewer/components/DashboardRenderer.jsx
- components/dashboards-web-component/src/viewer/components/dashboard-container-styles.css
In dashboards, the dashboard page height cannot be modified, and it always takes 100% of the screen height. This PR introduces the ability to resize a page using page properties and resize handlers. 
Resolves https://github.com/wso2/product-sp/issues/702
> Add options to adjust height of dashboard pages.

- components/dashboards-web-component/src/designer/components/WidgetOptionsConfiguration.jsx
This PR add multiple selections in select fields (`ENUM` type) in widget options. 
Refer the sample widget configuration fil below.
```json
{
"name": "MultiSelect Sample",
"id": "MultiSelectSample",
"thumbnailURL": "",
"configs": {
"options": [
{
"id": "make",
"title": "Make",
"type": {
"name": "ENUM",
"multiple": true,
"possibleValues": [
"Toyota",
"Nissan",
"Honda",
"Hyundai",
"Isuzu",
"Mitsubishi"
]
},
"defaultValue": ["Honda", "Isuzu"]
}
]
}
}
```
> Add multi-select support in select fields in widget options

- components/dashboards/org.wso2.carbon.dashboards.api/src/main/java/org/wso2/carbon/dashboards/api/internal/DashboardRestApi.java
- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/DashboardMetadataProvider.java
- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/WidgetMetadataProvider.java
- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/bean/export/Dashboard.java
- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/bean/export/DashboardPage.java
- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/bean/export/DashboardPageContent.java
- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/bean/export/WidgetCollection.java
- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/DashboardMetadataProviderImpl.java
- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/WidgetMetadataProviderImpl.java
This PR introduces a REST API to export a dashboard.
To get the dashboard with widget definitions, use the following URL.
```
https://localhost:9643/portal/apis/dashboards/<DASHBOARD_URL>/export
```
To download the dashboard with widget definitions, use the following URL.
```
https://localhost:9643/portal/apis/dashboards/<DASHBOARD_URL>/export?download=true
```
> Introduce REST API to export a dashboard

- components/dashboards-web-component/src/viewer/DashboardViewPage.jsx
- components/dashboards-web-component/src/viewer/components/LightBulbFill.jsx
- components/dashboards-web-component/src/viewer/components/LightBulbOutline.jsx
- components/dashboards-web-component/src/viewer/components/ThemeButton.jsx
Bring theme switch to the header as a button to improve userbility.
fixes : #1012
> Bring theme switch to the header as a button

- components/dashboards/org.wso2.carbon.dashboards.api/src/main/java/org/wso2/carbon/dashboards/api/internal/DashboardRestApi.java
- components/dashboards/org.wso2.carbon.dashboards.core/pom.xml
- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/DashboardMetadataProvider.java
- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/WidgetMetadataProvider.java
- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/bean/importer/DashboardArtifact.java
- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/bean/importer/Page.java
- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/bean/importer/PageContent.java
- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/bean/importer/WidgetCollection.java
- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/bean/importer/WidgetType.java
- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/exception/DashboardDeploymentException.java
- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/DashboardImporter.java
- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/DashboardMetadataProviderImpl.java
- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/WidgetMetadataProviderImpl.java
- pom.xml
In SP, there was no way to import dashboards other than copying the dashboard into the database. This PR introduces a dashboard importer so that dashboard JSONs resides at `<SP_HOME>/wso2/dashboards/resources/dashboards` are getting deployed upon the server startup. Dashboard JSONs can be generated via the export API.
> Add dashboard import funcationality

- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/DashboardMetadataProviderImpl.java
This PR fixes getting generated widget ID instead of widget title when exporting a dashboard.
> Fix getting generated widget Id when exporting a dashboard

- components/dashboards-web-component/src/common/WidgetRenderer.jsx
- components/dashboards-web-component/src/designer/components/DashboardRenderer.jsx
- components/dashboards-web-component/src/viewer/components/DashboardRenderer.jsx
Resolves #1041 1041
Dashboard designer will be able to change the displayed widget title name by using this feature. 
Widget author needs to add a config similar to the below in to his widgetConf.json file.
{
"name": "UserInfo",
"id": "UserInfo",
"thumbnailURL": "",
"displayName":"User Info",
"configs": {
"pubsub": {
"types": [
"publisher"
]
},
"options": [
{
"id": "header",
"title": "Header",
"type": {
"name": "BOOLEAN",
"possibleValues": [
true,
false
]
},
"defaultValue": true
},
**{
"id": "headerTitle",
"title": "Widget Display Name",
"type": {
"name": "TEXT",
"possibleValues": [
]
},
"defaultValue": "Title1"
}**
]
}
}
Afterwards by clicking the widget settings icon in the dashboard designer, user can change the display name.
> Add ability to configure widget title 

- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/bean/importer/PageContent.java
- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/DashboardMetadataProviderImpl.java
This PR fixes the issue with reading widget ID from generated widgets when exporting dashboards.
> Fix reading widget ID on dashboard export

- components/dashboards-web-component/src/common/WidgetRenderer.jsx
- components/dashboards-web-component/src/designer/components/DashboardRenderer.jsx
- components/dashboards-web-component/src/viewer/components/DashboardRenderer.jsx
$subject.
- Node v8.8.1
- NPM v5.4.2
- Tested using `UserInfo` widget with this [`widgetConf.json`](https://github.com/wso2/carbon-dashboards/pull/1042#issue-212959511)
> Fix widget config not geting saved in dashboard designer

- components/dashboards-web-component/package-lock.json
- components/dashboards-web-component/package.json
- pom.xml
- Bump base widget version to v1.4.0 in dashboard web component
- Bump carbon-analytics version to v2.0.419
- Bump carbon-analytics-common version to v6.0.70
> Dependencies version bumps for carbon-dashboards v4.0.37 release

- components/dashboards-web-component/pom.xml
- components/universal-widget/pom.xml
- pom.xml
- samples/widgets/Publisher/pom.xml
- samples/widgets/Subscriber/pom.xml
- samples/widgets/UserInfo/pom.xml
- samples/widgets/WidgetState/pom.xml
- samples/widgets/sales-dashboard-widgets/CustomersByProduct/pom.xml
- samples/widgets/sales-dashboard-widgets/CustomersPerYear/pom.xml
- samples/widgets/sales-dashboard-widgets/OverallProductInfo/pom.xml
- samples/widgets/sales-dashboard-widgets/OverallRevenueInfo/pom.xml
- samples/widgets/sales-dashboard-widgets/RevenueByCountry/pom.xml
- samples/widgets/sales-dashboard-widgets/RevenueByProduct/pom.xml
- samples/widgets/sales-dashboard-widgets/RevenueByProductWithUserPreferences/pom.xml
- samples/widgets/sales-dashboard-widgets/RevenueByRegion/pom.xml
- samples/widgets/sales-dashboard-widgets/RevenuePerYear/pom.xml
- samples/widgets/sales-dashboard-widgets/RevenuePercentage/pom.xml
$subject.
- Reduce build time of `carbon-dashboards` repo.
- Removed `npm install rimraf (clean)` and `npm run clean (clean)` executions from `exec-maven-plugin` in root `pom.xml`.
- Instead used `maven-clean-plugin` to delete `dist` & `node_modules` directories in the `clean` phase.
Ran local builds for a freshly cloned `carbon-dashboards` repo.
|                               | Before      | After   	     |
|------------------------- |-------------- |-------------- |
| `mvn clean`           | 02:05 min | 2.478 s     |
| `mvn clean install` | 10:24 min | 08:48 min |
- Confirmed that this PR doesn't commit any keys, …
> Remove defined executions for pre-clean & clean phases in exec-maven-plugin

- components/dashboards-web-component/public/locales/en.json
- components/dashboards-web-component/public/locales/fr.json
Some strings in the dashboard app use default strings due to missing the keys in the locale files. The missing links are included in the two files.
To make the Internationalization work better
> Add missing keys in locale files(en,fr) for React-Intl wrappers

- components/dashboards-web-component/src/listing/components/DashboardCard.jsx
- Fix permissions not being checked on rendering the more menu icon
- Fix cursor being default instead of pointer in the more menu icon
- Unit tests 
N/A
N/A
- Node v8.8.1
- NPM v5.4.2
- Firefox 61.0.1 on Ubuntu 16.04
- Chrome 68.0.3440.106 on Ubuntu 16.04
- Chromium 68.0.3440.106 on Ubuntu 16.04
> Fix more menu icon of a dashboard card in the dashboards listing page

- components/dashboards-web-component/src/designer/components/DashboardRenderer.jsx
- components/dashboards-web-component/src/designer/components/PagesSidePane.jsx
> In the Portal Component changing the height of the page is not affecting. If a newly created page is deleted the screen blacks out. Resolves #1093 
> Fix bugs
> Fix for not saving page height and page deletion blackout issue

- components/dashboards-web-component/src/viewer/DashboardViewPage.jsx
>  Embed widget (by having one widget in dashboard) with no banners
>  The goal is to embed a widget without having the banners in the dashboard
> Embed widget with no banners

- components/dashboards-web-component/public/locales/en.json
- components/dashboards-web-component/public/locales/fr.json
- components/dashboards-web-component/src/listing/components/DashboardCard.jsx
- components/dashboards-web-component/src/utils/DashboardExporter.js
- components/dashboards-web-component/src/utils/DashboardExportor.js
- components/dashboards-web-component/src/utils/apis/DashboardAPI.jsx
**Purpose**
> Providing the UI support to export dashboards
**Approach**
> The dashboard can be downloaded as a JSON file which contains,
-Dashboard definition
-Generated widget definitions
-Custom widget names
**Security checks**
>Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
>Ran FindSecurityBugs plugin and verified report? yes
>Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
**Test environment**
>NodeJs version : v8.8.1
>NPM version : 5.4.2
>JDK version: 1.8
>Operating system: Ubuntu 16.04
> Add dashboard export UI

- components/dashboards-web-component/package-lock.json
- components/dashboards-web-component/package.json
- components/dashboards-web-component/webpack.config.js
Upgrading Webpack to v4 along with the used loaders to their newest versions.
- `webpack` v3.4.1 --> v4.29.0
- `html-loader` v0.5.0 --> v0.5.5
- `css-loader` v0.28.4 --> v2.1.0
- `style-loader` v0.18.2 --> v0.23.1
- `url-loader` v0.6.2 --> v1.1.2
- Unit tests 
N/A
N/A
- Node v8.8.1
- NPM v5.4.2
- SP-4.3.0
> Upgrade Webpack to v4

- components/dashboards-web-component/.babelrc
- components/dashboards-web-component/package-lock.json
- components/dashboards-web-component/package.json
- components/dashboards-web-component/src/App.jsx
- components/dashboards-web-component/webpack.config.js
Upgrading Babel and related dependencies to newest versions.
- `babel-core` v6.25.0 --> `@babel/core` v7.2.2
- `babel-preset-es2015` v6.24.1 --> `@babel/preset-env` v7.3.1
- `babel-preset-stage-2` v6.24.1 --^
- `babel-preset-react` v6.24.1 --> `@babel/preset-react` v7.0.0
- `babel-register` v6.26.0 --> :x: 
- `babel-loader` v7.1.1 --> `babel-loader` v8.0.5
- `babel-polyfill` v6.26.0 --> :x: (refer [doc](https://babeljs.io/docs/en/next/babel-preset-env#usebuiltins))
- Unit tests 
N/A
N/A
- Node …
> Upgrade Babel to v7

- components/dashboards-web-component/src/viewer/DashboardViewPage.jsx
> Resolve issue #1134 SidePane doesn't close after selecting a page.
> [Dashboard] Close SidePane after selecting a page

- components/universal-widget/src/UniversalWidget.jsx
> Fix #1142 
When there is no data, previously rendered chart is not cleared and it remains the same.
If there is data
If there is no data
> [UniversalWidget] Clear the chart if data is empty

- components/dashboards-web-component/src/designer/DashboardCreatePage.jsx
- components/dashboards-web-component/test/sales-dashboard.json
- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/bean/DashboardMetadata.java
- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/bean/DashboardMetadataContent.java
- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/DashboardMetadataProviderImpl.java
- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/database/DashboardMetadataDao.java
- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/io/DashboardArtifactHandler.java
With the changes in [1], the JSON structure of each dashboard has been changed as follows.
```
$.dashboard.pages -> $.dashboard.content.pages
```
Because of this change, when importing a dashboard with the previous dashboard JSON structure, will not be saved properly. This PR fixes that issue.
[1] https://github.com/wso2/carbon-dashboards/pull/1144
> Fix issues in dashboard import feature

- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/DashboardImporter.java
- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/WidgetMetadataProviderImpl.java
> Fix PRIMARY_KEY violation when dashboards are imported twice

- components/shindig-server/src/main/resources/web.xml
> We added this configuration earlier for a fix we did for shindig but turns out, Identity Server packs its own web.xml file. Therefore, this is not needed.
> Remove unnecessary configuration from web.xml

- components/shindig-server/pom.xml
Remove xercesImpl jar files from the shindig-server since it is considered to be vulnerable.
> Remove xercesImpl jar files

- components/dashboards-web-component/src/listing/DashboardListingPage.jsx
- components/dashboards-web-component/src/utils/apis/DashboardAPI.jsx
- components/dashboards-web-component/src/widget-store/WidgetStore.jsx
- components/dashboards-web-component/src/widget-store/components/WidgetStoreCard.jsx
- components/dashboards/org.wso2.carbon.dashboards.api/src/main/java/org/wso2/carbon/dashboards/api/internal/DashboardRestApi.java
- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/DashboardMetadataProvider.java
- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/bean/roles/provider/Roles.java
- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/DashboardMetadataProviderImpl.java
In dashboards, even a role is not configured as a creator the user can create a dashboard and widget from the portal app. This PR fixes the issue.
Adding the following configuration in the dashboard's `deployment.yaml` file will allow only user users with role `<ROLE_ID>` to create dashboards and widgets within the portal app.
```yaml
wso2.dashboard:
roles:
creators:
- <ROLE_ID>
```
Resolving https://github.com/wso2/product-sp/issues/1038
> Fix dashboard creator role

- components/dashboards/org.wso2.carbon.dashboards.api/src/main/java/org/wso2/carbon/dashboards/api/internal/DashboardRestApi.java
- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/DashboardMetadataProvider.java
- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/bean/importer/DashboardArtifact.java
- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/DashboardImporter.java
- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/DashboardMetadataProviderImpl.java
This PR introduces support to import/export dashboard permissions while importing/exporting dashboards. 
Following REST API allows exporting dashboards with permissions.
```
/portal/apis/dashboards/<DASHBOARD_ID>/export?permissions=true
```
**Result:**
```json
{
"dashboard": { },
"widgets": { },
"permissions": {
"viewers": ["role_1", "role_2"],
"owners": ["role_1"],
"editors": ["role_2"]
}
}
```
> Support import/export dashboard permissions

- components/dashboards-web-component/src/designer/DashboardSettingsRoles.jsx
Suggestions in the dashboard settings page for different permission settings (Owner, Editor, Viewer) are getting cut off and this PR fix that issue.
> Fix auto complete suggestions getting cut-off

- components/dashboards-web-component/src/listing/components/DashboardCard.jsx
Menu which has Design, Settings, Export, Delete was not displayed for users with Dashboard Designer permission. This PR fixes that issue and display the menu with the Design and Export options for users with Dashboard Designer permission.
> Fix menu not appearing issue for users with Designer permission

- components/dashboards-web-component/src/auth/utils/AuthManager.jsx
Resolves https://github.com/wso2/analytics-apim/issues/737
DASHBOARD_USER cookie and other cookies are cleared from the browser at the sso logout.
> Clear cookies at the sso logout

- components/dashboards-web-component/src/utils/WidgetChannelManager.js
If there is no transfer between server and client, after a certain time, the WebSocket connection is closed automatically and this results in showing circular progress in widgets. 
This PR will re-open the web socket connection when it gets closed.
Resolves https://github.com/wso2/analytics-apim/issues/844
WebSocket client gets the ability re-open the connection in situations like temporary network problems etc.
This fix implemented in this PR is to listen to onclose events on the web socket client and when they occur, set a client side timeout to re-open the connection.
> Fix issue of websocket getting closed after an idle client

- components/dashboards-web-component/package-lock.json
- components/dashboards-web-component/package.json
- components/dashboards-web-component/public/index.hbs
- components/dashboards-web-component/src/common/Header.jsx
It is required to change the favicon icon of the analytics-dashboard app when customizing the theme of the dashboard application. This PR adds that capability.
Ability to white label dashboard application
A react library called react-helmet is used. And the default path to the favicon icon is retrieved from the DefaultDashboardThemeConfigProvider class and if its needed to be changed a config needs to be added to the deployment.yaml of the respective product.
Example:
In APIM Analytics deployment.yaml file of dashboard profile we have to add the below config. This CustomDashboardThemeConfigProvider will read the themeConfigResourcesPath from config and append tenant domain to its path at the end.
`
themeConfigProviderClass: org.wso2.analytics.apim.dashboards.theme.config.provider.CustomDas …
> Support to add a custom favicon

- components/dashboards-web-component/src/common/Header.jsx
- components/dashboards/org.wso2.carbon.dashboards.api/src/main/java/org/wso2/carbon/dashboards/api/internal/DashboardRestApi.java
- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/DashboardMetadataProvider.java
- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/DashboardThemeConfigProvider.java
- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/DefaultDashboardThemeConfigProvider.java
- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/bean/DashboardConfigurations.java
- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/DashboardMetadataProviderImpl.java
Resolves https://github.com/wso2/analytics-apim/issues/1007
To provide the ability to upload a single themeing zip from admin portal of APIM and reuse the same for Analytics as well.
This PR removes the api method "/theme-config-path" and add two api methods namely /favicon-path" and "/logo-path" and their impls
So if a user wants to change the current logo and favicon he needs to add a configuration similar to below in the deployment.yaml file.
`themeConfigProviderClass: org.wso2.analytics.apim.dashboards.theme.config.provider.CustomDashboardThemeConfigProvider`
` themeConfigResourcesPath: public/app`
`logoFileName: download.png`
`faviconFileName: favicon.ico`
> Fix tenant wise themeing paths

- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/bean/DashboardMetadataContent.java
- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/DashboardImporter.java
- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/DashboardMetadataProviderImpl.java
- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/io/DashboardArtifactHandler.java
- components/dashboards/org.wso2.carbon.dashboards.core/src/test/java/org/wso2/carbon/dashboards/core/internal/DashboardMetadataProviderImplTest.java
* Import the dashboard at every start
* Introduce readonly dashboard where UI not allowed to design dashboard
* Permission of the dashboards are updated only at start time, later on need to use UI to change them
> Improve dashboard imports

- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/DashboardMetadataProviderImpl.java
Wehn duplicate dashboard it's the owner should be currently logged in user. Also when adding a new dashboard, the owner should be the same way.
> Fixed owner when adding dashboard

- components/dashboards/org.wso2.carbon.dashboards.api/src/main/java/org/wso2/carbon/dashboards/api/internal/DashboardRestApi.java
Resolves https://github.com/wso2/analytics-apim/issues/883
Avoiding client side parsing errors.
This PR adds Content-type (text/plain) header for following endpoints to avoid client side parsing errors. 
`/roles/{username}/iscreator`
`/roles/{username}/iswidgetcreator`
`/favicon-path`
`/logo-path`
> Adds Content-type header for some endpoints.

- components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/DashboardMetadataProviderImpl.java
This PR resolves a PK violation in adding permissions while importing dashboards. This resolves https://github.com/wso2/carbon-dashboards/issues/1223. 
Fix is provided by @lasanthaS
> Fix https://github.com/wso2/carbon-dashboards/issues/1223

- components/dashboards-web-component/src/common/WidgetRenderer.jsx
This PR increases the timeout value for widget loader from 10000ms to 60000ms.
> Increase widget loader timeout

- base-widget/src/Widget.jsx
Fixes https://github.com/wso2/analytics-apim/issues/1413
This PR increases the Analytics Dashboard Widget Timeout from 2000 to 60000.
> Increase Analytics Dashboard Widget Timeout

- components/dashboards-web-component/src/common/Header.jsx
- components/dashboards-web-component/src/viewer/DashboardViewPage.jsx
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
This fixes the issue where the print menu would only show up for one second and could not be triggered to return.
Changed the logo to use both the logo from the Header and the navigation menu icon from the DashboardViewPage.
The click event was moved to the navigation menu icon instead of the logo link.
> List all JDK versions, operating systems, databases, and …
> Fixed Print Menu Not Appearing

- base-widget/package.json
- base-widget/src/Widget.jsx
Aims to fix https://github.com/wso2/analytics-apim/issues/1413
This PR bumps version of @wso2-dashboards/widget from 1.5.0 to 1.5.1 in order to publish node module with changes to registry.
> Bump @wso2-dashboards/widget version to 1.5.1

- components/dashboards-web-component/src/auth/SecuredRouter.jsx
This PR fixes an issue where unauthorized logs were printing continuously when websocket connection closes while the user is viewing a dashboard.
Related issue: https://github.com/wso2/analytics-apim/issues/1515
> Fix continuous unauthorized log issue in dashboards
