wso2/carbon-dashboards

apps/portal/controllers/apis/assets.jag, apps/portal/controllers/apis/dashboards.jag
renaming 'undefined' to undefined
=> Refactoring

apps/portal/controllers/apis/analytics.jag
Error when selecting an event stream for the 'Analytic Table/Event Stream' parameter when creating a gadget in 'Dashboard Designer'.
=> JIRA Fixed - CEP - 1293 - Error when selecting an event stream

apps/portal/theme/templates/designer.jag
This will add "CREATE GADGET" link to edit preview of dashboard.
=> Fixed DAS-21

apps/portal/js/wizard.js
Text message added for batch preview panel by saying "You will not view all records of large data sets her"
=> Text message added for batch preview panel

apps/portal/theme/templates/designer.jag, apps/portal/theme/templates/index.jag
I have added id for the elements which can identify the elements during the UI testcases.
=> Adding ID for dashboard and dashBoard layout for UI testcases

apps/portal/extensions/stores/fs/index.js, apps/portal/modules/user.js, apps/portal/modules/utils.js
fix for jira issue UES-636 (Dashboard settings shows supertenant roles for editors and viewers of subtenant)
=> Carbon dashboards sidias 0.2

apps/portal/js/designer.js
Also added the fix for sanitation doesn't work in designer page property toggle menu due to recent class name changes
=> Fixed the issue with backspace and delete not working in the firefox

apps/portal/css/common.css, apps/portal/css/dashboard.css, apps/portal/css/designer.css, apps/portal/extensions/components/gadget/index.js, apps/portal/extensions/locales/locale_default.json, apps/portal/js/dashboard.js, apps/portal/js/designer.js, apps/portal/js/gadget-properties.js, apps/portal/js/ues-dashboards.js, apps/portal/modules/dashboards.js, apps/portal/store/carbon.super/gadget/usa-map/index.xml, apps/portal/theme/templates/dashboard.jag, apps/portal/theme/templates/designer.jag
Related to JIRA: https://wso2.org/jira/browse/UES-634
=> Fixed the issue which banners are not getting saved in tenant mode

apps/portal/store/carbon.super/gadget/publisher/gadget.json, apps/portal/store/carbon.super/gadget/publisher/index.xml, apps/portal/store/carbon.super/gadget/subscriber/gadget.json, apps/portal/store/carbon.super/gadget/subscriber/index.xml, apps/portal/store/carbon.super/gadget/usa-map/gadget.json, apps/portal/store/carbon.super/gadget/usa-map/index.xml
UI and the functionality of the gadgets have been revised and changed
=> Updated the Publisher and Subscriber gadgets

apps/portal/css/dashboard.css, apps/portal/js/dashboard.js, apps/portal/js/designer.js, apps/portal/theme/templates/dashboard.jag
* Fixed UI alignment issue
* Removed gadget options from anon dashboard
=> Fixed issues in dashboard view page

apps/portal/js/create.js
Public Jira - [https://wso2.org/jira/browse/UES-892]
=> [UES-892] Rewording the message displayed when duplicate dashboard name is used

apps/portal/js/designer.js
To avoid concurrent operations on a checkbox, the checkbox was disabled before updating the component properties, and enabled back after updating. 
Public JIRA: https://wso2.org/jira/browse/UES-825
=> [UES-825] "RegistryException: Resource content is empty" observed with concurrent operations

apps/portal/routers/pages.jag, apps/portal/routers/tenant.jag
This will redirect the http request coming from the users to login to https request to ensure it is served through secure channel.
Public Jira -[https://wso2.org/jira/browse/UES-898]
=> [UES-898] Making https default for login operation

apps/portal/css/custom.css
Introduce the horizontal grid in the design view
=> [UES-896] Introduce horizontal grid in the design view

apps/portal/css/custom.css, apps/portal/css/designer.css, apps/portal/theme/templates/dashboard-settings.jag
Fixed the style issue in Save/Cancel Button in Settings page
=> Fixed the style issue in Save/Cancel Button in Settings page/ Grid in designer View

apps/portal/modules/api.js
This is to address the privacy concerns raised in ANLYESB-80.
=> Changing the log level of the session cookie entry

apps/portal/controllers/apis/login.jag, apps/portal/controllers/error-pages/error400.html, apps/portal/controllers/error-pages/error401.html, apps/portal/controllers/error-pages/error403.html, apps/portal/controllers/error-pages/error404.html, apps/portal/controllers/error-pages/error405.html, apps/portal/controllers/error-pages/error500.html, apps/portal/controllers/gadgets.jag, apps/portal/controllers/login.jag, apps/portal/css/error.css, apps/portal/extensions/locales/locale_default.json, apps/portal/extensions/locales/locale_si.json, apps/portal/jaggery.conf, apps/portal/js/error.js, apps/portal/js/gadget.js, apps/portal/theme/templates/login.jag, apps/portal/theme/templates/pubsub-gadget.jag
=> Restricting login API to post method and changing code as per other code review comments.

apps/portal/js/dashboard.js, apps/portal/store/carbon.super/fs/gadget/usa-social/index.xml, components/shindig-server/src/main/resources/features.txt
https://wso2.org/jira/browse/UES-933
https://wso2.org/jira/browse/UES-944
=> Fixing UES-933 and UES-944

apps/portal/controllers/apis/assets.jag, apps/portal/controllers/dashboards.jag, apps/portal/extensions/components/gadget/index.js, apps/portal/extensions/locales/locale_default.json, apps/portal/extensions/locales/locale_si.json, apps/portal/js/ues-dashboards.js, apps/portal/js/ues-store.js, apps/portal/theme/templates/dashboard.jag, apps/portal/theme/templates/designer.jag, components/shindig-wso2-features/src/main/javascript/wso2features/container.site.gadget/feature.xml, components/shindig-wso2-features/src/main/javascript/wso2features/container.site.gadget/gadget_holder.js, components/shindig-wso2-features/src/main/javascript/wso2features/container.site.gadget/gadget_site.js, components/shindig-wso2-features/src/main/javascript/wso2features/features.txt
Public Jira - https://wso2.org/jira/browse/UES-974
=> [UES-974] Make the security time-out of shindig to be configurable

apps/portal/js/dashboard.js, apps/portal/js/ues-gadgets.js
Public Jira - https://wso2.org/jira/browse/UES-989
=> Fixing UES-989

apps/portal/controllers/apis/createGadget.jag, apps/portal/controllers/index.jag, apps/portal/controllers/store.jag, apps/portal/controllers/temp.jag, apps/portal/js/wizard.js, apps/portal/routers/tenant.jag, apps/portal/theme/templates/create-gadget.jag
Public Jira- https://wso2.org/jira/browse/UES-1016
=> [UES-1016]Fix for tenant flow

apps/portal/controllers/apis/createGadget.jag, apps/portal/controllers/store.jag, apps/portal/controllers/temp.jag, apps/portal/jaggery.conf, apps/portal/js/wizard.js, apps/portal/routers/tenant.jag, apps/portal/theme/templates/create-gadget.jag
Public Jira - https://wso2.org/jira/browse/UES-1016
=> [UES-1016]Fixing tenant flow and preview problem

apps/portal/css/gadget-custom.css, apps/portal/js/dashboard-theme.js, apps/portal/js/gadget.js, apps/portal/js/ues-dashboards.js, apps/portal/theme/templates/gadget.jag
Public Jira - https://wso2.org/jira/browse/UES-1015
=> [UES-1015]Adding page loading for embeddable gadget

apps/portal/css/designer.css, apps/portal/extensions/locales/locale_default.json, apps/portal/js/designer.js, apps/portal/resources/extensions/es/src/dsgadget/themes/default/js/gadget_conf_reader.js, apps/portal/theme/templates/designer.jag
Public Jira - https://wso2.org/jira/browse/UES-1014
=> [UES-1014] Add new gadget/layout button at the end of the gadget listing and layout listings when user designs dashboard

apps/portal/resources/extensions/es/src/dsgadget/asset.js
Public Jira - https://wso2.org/jira/browse/UES-1028
=> [UES-1028]Creating gadgets in third-party store - Thumbnail image does not show

apps/portal/modules/assets.js, apps/portal/theme/templates/assets.jag, apps/portal/theme/templates/includes/portal-footer.jag
Public Jira - https://wso2.org/jira/browse/UES-1018, https://wso2.org/jira/browse/UES-1022
=> Fixing UES-1018 and UES-1022

apps/portal/controllers/dashboard-settings.jag, apps/portal/extensions/locales/locale_default.json, apps/portal/js/dashboard-settings.js, apps/portal/modules/constants.js, apps/portal/theme/templates/dashboard-settings.jag, apps/portal/theme/templates/designer.jag, apps/portal/theme/templates/index.jag, components/dashboard-deployment/src/main/resources/META-INF/component.xml
Public Jira - https://wso2.org/jira/browse/UES-1030
=> [UES-1030] Removing the dashboard settings from global permission tree

apps/portal/controllers/dashboards.jag, apps/portal/controllers/includes/renderer.jag, apps/portal/extensions/locales/locale_default.json, apps/portal/js/dashboard.js, apps/portal/js/store-manager.js, apps/portal/modules/dashboards.js, apps/portal/modules/utils.js, apps/portal/theme/templates/dashboard.jag, apps/portal/theme/templates/designer.jag
Public Jiras 
https://wso2.org/jira/browse/UES-1052
https://wso2.org/jira/browse/UES-1057
https://wso2.org/jira/browse/UES-1058
https://wso2.org/jira/browse/UES-1059
https://wso2.org/jira/browse/UES-1060
=> Fixing UES-1052, UES-1057, UES-1058, UES-1059 and UES-1060

apps/portal/css/settings.css, apps/portal/extensions/locales/locale_default.json, apps/portal/extensions/locales/locale_si.json, apps/portal/theme/templates/dashboard-settings.jag
Public Jira - https://wso2.org/jira/browse/UES-1054
=> Fixing UES-1054

apps/portal/js/designer.js
Public Jira - https://wso2.org/jira/browse/UES-1088
=> Fixing UES-1088

apps/portal/css/common.css, apps/portal/css/custom.css, apps/portal/css/designer.css, apps/portal/css/portal.css, apps/portal/js/assets.js, apps/portal/theme/templates/assets.jag, apps/portal/theme/templates/designer.jag, apps/portal/theme/templates/index.jag
- Dashboard listing page truncate styling
- Defective dashboard alert icon & it's color fix
- Show store selector if has multiple stores only in Asset listing page
=> Few style fixes

apps/portal/js/designer.js
Public Jira - https://wso2.org/jira/browse/UES-1089
=> Fixing UES-1089

apps/portal/js/designer.js
Fix for the jira https://wso2.org/jira/browse/UES-1083
=> Fix the issue UES-1083

apps/portal/extensions/locales/locale_default.json, apps/portal/js/create.js, apps/portal/js/ues-dashboards.js, apps/portal/theme/templates/designer.jag
Public Jira - https://wso2.org/jira/browse/UES-1076, https://wso2.org/jira/browse/UES-1086
=> Fixing UES-1076 and UES-1086

apps/portal/js/designer.js, apps/portal/theme/templates/designer.jag
Public Jira - https://wso2.org/jira/browse/UES-1099
https://wso2.org/jira/browse/UES-1100
=> Fixing UES-1099 and UES-1100

apps/portal/css/portal.css
Public Jira - https://wso2.org/jira/browse/UES-1114
=> [UES-1114] When deleting a dashboard with a long name the name goes out from the delete conformation box

apps/portal/extensions/providers/rdbms/api.js, apps/portal/extensions/providers/rdbms/config.json
Public Jira - https://wso2.org/jira/browse/UES-1119
=> Fixing UES-1119

apps/portal/js/designer.js
Public Jira - https://wso2.org/jira/browse/UES-1123
=> Fixing UES-1123

README.md, components/org.wso2.carbon.dashboard.portal/src/main/fragments/bar-chart/public/conf/conf.json, components/org.wso2.carbon.dashboard.portal/src/main/fragments/pie-chart/public/conf/conf.json, components/org.wso2.carbon.dashboard.portal/src/main/fragments/publisher/public/conf/conf.json, components/org.wso2.carbon.dashboard.portal/src/main/fragments/subscriber/public/conf/conf.json, components/org.wso2.carbon.dashboard.view/src/main/modules/dashboard-util.js, components/org.wso2.carbon.dashboard.view/src/main/modules/user-util.js
related public jira: https://wso2.org/jira/browse/UES-1130
related redmine: https://redmine.wso2.com/issues/5599
=> Add gadget level permission configurations and added dashboard utils and user utils - UES-1130

README.md
related public jira: https://wso2.org/jira/browse/UES-1130
related redmine: https://redmine.wso2.com/issues/5599
=> Updated the readme - UES-1130

components/org.wso2.carbon.dashboards.portal/src/main/bindings.yaml, components/org.wso2.carbon.dashboards.portal/src/main/component.yaml
This change is done due to change in carbon-uuf.
=> Remove bindings.yaml and include component.yaml

README.md
=> Update Readme.md with images

components/org.wso2.carbon.dashboards.designer/src/main/fragments/footer/footer.hbs, components/org.wso2.carbon.dashboards.designer/src/main/fragments/header/header.hbs, components/org.wso2.carbon.dashboards.designer/src/main/fragments/left-nav-bar/public/js/left-nav-bar.js, components/org.wso2.carbon.dashboards.designer/src/main/lang/en_US.properties, components/org.wso2.carbon.dashboards.designer/src/main/layouts/designer.hbs, components/org.wso2.carbon.dashboards.designer/src/main/pages/{id}.hbs, components/org.wso2.carbon.dashboards.designer/src/main/public/css/designer.css, components/org.wso2.carbon.dashboards.designer/src/main/public/lib/theme-wso2_1.0/css/theme-wso2.css, components/org.wso2.carbon.dashboards.portal/pom.xml, components/org.wso2.carbon.dashboards.portal/src/main/app.yaml, components/org.wso2.carbon.dashboards.portal/src/main/fragments/dashboard-list-thumbnail/dashboard-list-thumbnail.hbs, components/org.wso2.carbon.dashboards.portal/src/main/fragments/label/label.hbs, components/org.wso2.carbon.dashboards.portal/src/main/layouts/dashboardView.hbs, components/org.wso2.carbon.dashboards.portal/src/main/layouts/main.hbs, components/org.wso2.carbon.dashboards.portal/src/main/pages/dashboard/{id}.hbs, components/org.wso2.carbon.dashboards.portal/src/main/pages/index.hbs, components/org.wso2.carbon.dashboards.portal/src/main/public/css/dashboard.css, components/org.wso2.carbon.dashboards.portal/src/main/public/css/portal.css, components/org.wso2.carbon.dashboards.view/src/main/fragments/dashboard-view/public/js/dashboard.js
This commit is to use existing libraries available in UUF - jquery, wso2_theme and etc. Currently it uses separate libraries without using existing libraries available in UUF. 
Resolves #468
=> Use libraries available in UUF-Commons

components/org.wso2.carbon.dashboards.designer/src/main/layouts/designer.hbs, components/org.wso2.carbon.dashboards.designer/src/main/public/css/designer.css, components/org.wso2.carbon.dashboards.designer/src/main/public/lib/theme-wso2_1.0/css/theme-wso2.css, components/org.wso2.carbon.dashboards.portal/src/main/layouts/dashboardView.hbs, components/org.wso2.carbon.dashboards.portal/src/main/public/css/dashboard.css
This PR resolves several issues introduced in PR 467
=> Modify the PR 467

components/org.wso2.carbon.dashboards.designer/src/main/component.yaml, components/org.wso2.carbon.dashboards.designer/src/main/fragments/dashboard-designer/public/js/designer.js, components/org.wso2.carbon.dashboards.designer/src/main/fragments/sidebar-left-nav-config/public/js/widget-conf.js, components/org.wso2.carbon.dashboards.designer/src/main/fragments/sidebar-left-nav-config/sidebar-left-nav-config.hbs, components/org.wso2.carbon.dashboards.designer/src/main/fragments/widget-box/widget-box.hbs, components/org.wso2.carbon.dashboards.designer/src/main/lang/en_US.properties, components/org.wso2.carbon.dashboards.designer/src/main/layouts/designer.hbs
This commit will introduce a new sidebar(RHS), which is going to host widget configuration, pub-sub wiring etc..
=> Introducing widget configuration side-bar

apps/portal/theme/templates/includes/global-navigation.jag
This fix the issue https://wso2.org/jira/browse/CDASHBOARD-9
=> Fix CDASHBOARD-9

components/org.wso2.carbon.dashboards.view/src/main/fragments/dashboard-view/public/js/common/common.js, components/org.wso2.carbon.dashboards.view/src/main/fragments/dashboard-view/public/js/dashboard.js
This will enable the widget wiring capability within dashboard view.
=> Introduce pub/sub capability to the dashboard view

components/org.wso2.carbon.dashboards.designer/src/main/fragments/dashboard-designer/dashboard-designer.hbs, components/org.wso2.carbon.dashboards.designer/src/main/fragments/dashboard-designer/public/js/common/common.js, components/org.wso2.carbon.dashboards.designer/src/main/fragments/dashboard-designer/public/js/designer.js, components/org.wso2.carbon.dashboards.designer/src/main/fragments/layout-list-container/layout-list-container.hbs, components/org.wso2.carbon.dashboards.designer/src/main/fragments/layout-list-container/public/js/layout.js
- Layout drag/drop changed to click and apply method
- Implement destroyDashboard() and applyLayout() functions
- Noty JS library added from carbon-uuf-common
- User confirmation added to the layout change UI.
=> Implement dynamic layout change functionality to the designer

components/org.wso2.carbon.dashboards.designer/src/main/fragments/widget-list-container/widget-list-container.hbs, components/org.wso2.carbon.dashboards.designer/src/main/public/css/designer.css
=> Add dashboard-icon using WSO2-icons

components/org.wso2.carbon.dashboards.designer/src/main/fragments/bar-chart/conf/widgetConf.json, components/org.wso2.carbon.dashboards.designer/src/main/fragments/dashboard-designer/dashboard-designer.js, components/org.wso2.carbon.dashboards.designer/src/main/fragments/dashboard-designer/public/js/common/common.js, components/org.wso2.carbon.dashboards.designer/src/main/fragments/dashboard-designer/public/js/common/widget-renderer.js, components/org.wso2.carbon.dashboards.designer/src/main/fragments/dashboard-designer/public/js/designer.js, components/org.wso2.carbon.dashboards.designer/src/main/fragments/pie-chart/conf/widgetConf.json, components/org.wso2.carbon.dashboards.designer/src/main/fragments/widget-box/widget-box.hbs
- Widgets which are there in dashboard will not be listed in the listing page
- Widget configuration icon will be only visible if particular widget is a configurable one (subscriber etc..)
=> Set widget listing and widget configuration visibility

apps/portal/extensions/authentication/sso-login.jag
This PR adds support to Sanitize Request Parameters in sso-login.jag.
=> Sanitize Request Parameters

components/org.wso2.carbon.dashboards.designer/src/main/fragments/dashboard-designer/dashboard-designer.js, components/org.wso2.carbon.dashboards.designer/src/main/fragments/dashboard-designer/public/js/designer.js, components/org.wso2.carbon.dashboards.view/src/main/fragments/dashboard-view/public/js/dashboard.js
In this PR, the existing dashboard.json file has been restructured to simplify and support features such as multiple hierarchical pages (resolves #492). A sample dashboard.json is as follows.
```
{
"name": "Finance Dashboard",
"id": "finance",
"version": "1.0.0",
"description": "Lorem ipsum dolor sit amet",
"pages": {
"overview": {
"name": "Overview",
"layout": [
{
"id": "b0001",
"x": 0,
"y": 0,
"width": 6,
"height": 4,
"widget": {
"id": "org.wso2.carbon.dashboards.widget.bar-chart",
"displayName": "Bar Chart",
"configurations": {}
}
},
{
"id": "b0002",
"x": 7,
"y": 0,
"width": 6,
"height": 4,
"widget": {}
},
{
"id": "b0003",
"x": 0,
"y": 5,
"width": 12,
"height": 2,
"widget": {}
}
],
"pages": {}
},
"finance": {
"name": "Finance",
"layout": [],
"pages": {
"name": "Financial Growth", …
```
=> Restructure dashboard.json

components/org.wso2.carbon.dashboards.view/src/main/fragments/dashboard-view/public/js/common/widget-renderer.js, components/org.wso2.carbon.dashboards.view/src/main/fragments/dashboard-view/public/js/dashboard.js
This PR introduces following fixes.
* Fix pubsub wiring issue in dashboard view
* Fix not rendering widget hbs when render callback is specifiied.
=> Fix Issues in widget wiring and rendering

components/org.wso2.carbon.dashboards.view/src/main/fragments/dashboard-view/public/js/common/widget-renderer.js, components/org.wso2.carbon.dashboards.view/src/main/fragments/dashboard-view/public/js/dashboard.js
This PR will add the render order functionality to the dashboard view component.
=> Widget render order implementation for view component

components/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/provider/impl/DashboardMetadataProviderImpl.java, components/org.wso2.carbon.dashboards.designer/src/main/fragments/dashboard-create/public/js/dashboard-create.js, components/org.wso2.carbon.dashboards.designer/src/main/fragments/dashboard-designer/public/js/designer.js
This PR resolves following issues.
* Error in creating a dashboard.
* NPE occurs when the dashboard directory does not exist.
* Error in add block functionality.
=> Fix dashboard issues

components/org.wso2.carbon.dashboards.designer/src/main/fragments/dashboard-create/public/js/dashboard-create.js, components/org.wso2.carbon.dashboards.designer/src/main/fragments/left-nav-bar/left-nav-bar.hbs, components/org.wso2.carbon.dashboards.designer/src/main/fragments/sidebar-nav-layouts/sidebar-nav-layouts.hbs, components/org.wso2.carbon.dashboards.designer/src/main/fragments/sidebar-nav-widgets/sidebar-nav-widgets.hbs, components/org.wso2.carbon.dashboards.designer/src/main/lang/en_US.properties, components/org.wso2.carbon.dashboards.sample.portal.feature/src/main/fragments/task-bar/task-bar.hbs, components/org.wso2.carbon.dashboards.view/src/main/fragments/dashboard-view/public/js/dashboard.js
This PR will provide following changes,
- Remove alert in dashboard-create.js 			
- Fix issue in resizing widgets in view 			
- Replce Gadgets with Widgets 			
- Remove navigation panel in portal app 			
- Remove show grid radio button
Resolves #529 
Resolves #535
=> Fixing issues

components/org.wso2.carbon.dashboards.designer/src/main/fragments/dashboard-designer/dashboard-designer.hbs, components/org.wso2.carbon.dashboards.designer/src/main/lang/en_US.properties, components/org.wso2.carbon.dashboards.sample.store/src/main/fragments/pie-chart/public/js/draw.js, components/org.wso2.carbon.dashboards.view/src/main/fragments/dashboard-view/public/js/dashboard.js
This PR provides following changes,
- Use pie chart in sample widget
- Prevent displaying empty blocks in view 			
- Fix issue in View Dashboard button
Resolves #531 
Resolves #538 
Resolves #528
=> Minor bug fixes

components/org.wso2.carbon.dashboards.view/src/main/fragments/dashboard-view/public/js/dashboard.js
=> Fix widget-state issue in new pages

apps/portal/modules/user.js
This is applied when Account Recovery and Credential Management features are installed.
=> Lock user account when multiple retries are made

components/dashboards-web-component/package-lock.json, components/dashboards-web-component/package.json, components/dashboards-web-component/public/css/dashboard.css, components/dashboards-web-component/src/DashboardRenderingComponent.jsx, components/dashboards-web-component/src/PagesNavigationPanel.jsx
=> Implement dark-light theme support

components/dashboards-web-component/public/css/dashboard.css, components/dashboards-web-component/src/DashboardListing.jsx, components/dashboards-web-component/src/DashboardRenderingComponent.jsx, components/dashboards-web-component/src/DashboardThumbnail.jsx, components/dashboards-web-component/src/DashboardView.jsx, components/dashboards-web-component/src/DashboardViewHeader.jsx, components/dashboards-web-component/src/Header.jsx, components/dashboards-web-component/src/PagesNavigationPanel.jsx
This PR contains Material UI integration with Dashboard listing and view pages.
(Resolves https://github.com/wso2/carbon-dashboards/issues/563)
=> Modified UI using Material UI

README.md, components/dashboards-web-component/src/PagesNavigationPanel.jsx, components/dashboards-web-component/test/dashboard-apis.test.js
This PR will introduce following,
- Update the REST APIs test-cases
- Add Readme file to repository
- Add browser persistence to theme support
=> Update test-cases, readme file and add browser persistence to theme support

README.md
This PR will resolve the issues in readme.md file
=> Fix issues in readme.md

components/dashboards-web-component/src/utils/dashboard-apis.js, components/dashboards/org.wso2.carbon.dashboards.api/src/main/java/org/wso2/carbon/dashboards/api/DashboardMetadataAPI.java
=> Refactor dashboard APIs

components/dashboards-web-component/public/css/dashboard.css, components/dashboards-web-component/src/DashboardDesigner.jsx, components/dashboards-web-component/src/DashboardRenderingComponent.jsx, components/dashboards-web-component/src/DashboardThumbnail.jsx, components/dashboards-web-component/src/DashboardView.jsx, components/dashboards-web-component/src/PagesNavigationPanel.jsx, components/dashboards-web-component/src/PortalRouter.jsx, components/dashboards-web-component/src/WidgetListThumbnail.jsx, components/dashboards-web-component/src/WidgetLoadingComponent.jsx, components/dashboards-web-component/src/WidgetsList.jsx, components/dashboards-web-component/src/utils/dashboard-utils.js, components/dashboards-web-component/src/utils/widget-info-apis.js, components/dashboards/org.wso2.carbon.dashboards.api/pom.xml, components/dashboards/org.wso2.carbon.dashboards.api/src/main/java/org/wso2/carbon/dashboards/api/WidgetInfoProviderAPI.java, components/dashboards/org.wso2.carbon.dashboards.core/pom.xml, components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/DataHolder.java, components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/ServiceComponent.java, components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/widget/info/WidgetInfoComponent.java, components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/widget/info/WidgetInfoProviderImpl.java, pom.xml
This PR will introduce will introduce initial dashboard designer implementation and widget listing in the dashboard designer component. This will also introduce APIS which can be used get widget related information.
Resolves #584
=> Widget Listing in Dashboard designer and initial designer implmentation

components/dashboards-web-component/public/css/dashboard.css, components/dashboards-web-component/src/DashboardCreatePage.jsx, components/dashboards-web-component/src/DashboardDesigner.jsx, components/dashboards-web-component/src/DashboardListing.jsx, components/dashboards-web-component/src/DashboardRenderingComponent.jsx, components/dashboards-web-component/src/DashboardThumbnail.jsx, components/dashboards-web-component/src/DashboardView.jsx, components/dashboards-web-component/src/PortalRouter.jsx, components/dashboards-web-component/src/WidgetListThumbnail.jsx, components/dashboards-web-component/src/WidgetLoadingComponent.jsx, components/dashboards-web-component/src/WidgetsList.jsx, components/dashboards-web-component/src/utils/dashboard-utils.js
=> Add dashboard create implementation

components/dashboards-web-component/package.json, components/dashboards-web-component/public/css/dashboard.css, components/dashboards-web-component/public/css/designer.css, components/dashboards-web-component/src/DashboardCreatePage.jsx, components/dashboards-web-component/src/DashboardDesigner.jsx, components/dashboards-web-component/src/DashboardListing.jsx, components/dashboards-web-component/src/DashboardRenderingComponent.jsx, components/dashboards-web-component/src/DashboardSettings.jsx, components/dashboards-web-component/src/DashboardThumbnail.jsx, components/dashboards-web-component/src/PortalRouter.jsx, components/dashboards-web-component/src/WidgetLoadingComponent.jsx, components/dashboards-web-component/src/WidgetsList.jsx, components/dashboards-web-component/src/designer/components/PageEntry.jsx, components/dashboards-web-component/src/designer/components/PagesPanel.jsx
=> Dashboard settings pages and UI fixes

README.md
> This is to test auto-release with the repository.
=> Update Readme file to test auto-release

components/dashboards-web-component/src/designer/DashboardDesigner.css, components/dashboards-web-component/src/designer/DashboardDesigner.jsx, components/dashboards-web-component/src/designer/components/WidgetConfigurationPanel.jsx, components/dashboards-web-component/src/designer/components/WidgetsList.jsx, components/dashboards-web-component/src/utils/DashboardRenderingComponent.jsx, components/dashboards-web-component/src/utils/DashboardUtils.jsx, components/dashboards-web-component/src/utils/PubSubComponent.jsx, components/dashboards-web-component/src/utils/WidgetLoadingComponent.jsx, components/dashboards/org.wso2.carbon.dashboards.api/src/main/java/org/wso2/carbon/dashboards/api/WidgetInfoProviderAPI.java, components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/bean/widget/PubSub.java, components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/bean/widget/WidgetConfigs.java, components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/bean/widget/WidgetMetaInfo.java, components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/widget/info/WidgetInfoProviderImpl.java
Introduce initial implementation of pubsub feature for dashboard component.
Users can introduce communication between widgets in the dashboard with this pubsub feature.
> Used Event Emitter of GoldenLayout library as the communication channel to implement the feature.
> This feature will introduce a mechanism to communicate between widgets in the dashboard
=> Implement the initial version of pubsub feature

components/dashboards-web-component/pom.xml, components/dashboards-web-component/src/designer/components/WidgetsList.jsx, components/dashboards/org.wso2.carbon.dashboards.api/pom.xml, components/dashboards/org.wso2.carbon.dashboards.core/pom.xml, features/org.wso2.carbon.dashboards.api.feature/pom.xml, features/org.wso2.carbon.dashboards.portal.feature/pom.xml, pom.xml, samples/components/org.wso2.carbon.dashboards.samples.endpoint/pom.xml, samples/features/org.wso2.carbon.dashboards.samples.feature/pom.xml, samples/pom.xml
This PR fixes an intermittent issue in adding widgets to a newly created dashboard. (Resolved #618)
=> Fix issue in adding widgets to a dashboard.

components/dashboards-web-component/pom.xml, components/dashboards/org.wso2.carbon.dashboards.api/pom.xml, components/dashboards/org.wso2.carbon.dashboards.core/pom.xml, features/org.wso2.carbon.dashboards.api.feature/pom.xml, features/org.wso2.carbon.dashboards.portal.feature/pom.xml, pom.xml
Clean-up `pom.xml` files.
- Code formatting.
- Fix license headers.
- Add missing dependencies.
- Remove unnecessary dependencies.
- Remove unnecessary plugins,
- Remove `<repositories>` and `<pluginRepositories>` from root `pom.xml` as they are inherited from WSO2 parent `pom.xml`.
- Fix OSGi imports, exports, and private package headers.
=> Clean-up pom.xml files

components/dashboards-web-component/src/utils/apis/DashboardAPI.jsx, components/dashboards-web-component/src/utils/apis/WidgetAPI.jsx, components/dashboards/org.wso2.carbon.dashboards.api/pom.xml, components/dashboards/org.wso2.carbon.dashboards.api/src/main/java/org/wso2/carbon/dashboards/api/internal/DashboardRestApi.java, components/dashboards/org.wso2.carbon.dashboards.api/src/main/java/org/wso2/carbon/dashboards/api/internal/WidgetRestApi.java, pom.xml
> This PR will secure the backend APIs available for Portal app.
> This PR will secure the backend APIs available for Portal app.
> We have used the cutdown version of KM that is available in carbon-common-analytics repository. We have used the interceptor available in the above-mentioned repository to secure the backend end APIs. It will make calls to the cutdown version of KM and validate the keys.
> java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build …
=> Secure product's backend APIs

components/dashboards-web-component/public/css/dashboard.css, components/dashboards-web-component/public/index.hbs, components/dashboards-web-component/src/auth/Login.jsx, components/dashboards-web-component/src/common/Global.css, components/dashboards-web-component/src/common/components/Header.css, components/dashboards-web-component/src/common/components/Header.jsx, components/dashboards-web-component/src/designer/DashboardCreatePage.jsx, components/dashboards-web-component/src/designer/DashboardDesigner.css, components/dashboards-web-component/src/designer/DashboardDesigner.jsx, components/dashboards-web-component/src/designer/DashboardSettings.jsx, components/dashboards-web-component/src/listing/DashboardListing.jsx, components/dashboards-web-component/src/listing/DashboardThumbnail.jsx
=> Dashboard designer UI fixes

components/dashboards-web-component/src/auth/utils/AuthManager.jsx, pom.xml
> Upgrade analytics common version and Fix the logout issue
=> Upgrade analytics common version and Fix the logout issue

pom.xml
Bump carbon analytics-common version to v6.0.16
=> Bump carbon analytics-common version to v6.0.16

components/dashboards-web-component/pom.xml, components/dashboards/org.wso2.carbon.dashboards.api/pom.xml, components/dashboards/org.wso2.carbon.dashboards.core/pom.xml, features/org.wso2.carbon.dashboards.api.feature/pom.xml, features/org.wso2.carbon.dashboards.portal.feature/pom.xml, pom.xml, samples/components/org.wso2.carbon.dashboards.samples.endpoint/pom.xml, samples/features/org.wso2.carbon.dashboards.samples.feature/pom.xml, samples/pom.xml, samples/widgets/CpuUsage/pom.xml, samples/widgets/LoadAverage/pom.xml, samples/widgets/MemoryUsage/pom.xml, samples/widgets/Publisher/pom.xml, samples/widgets/ServerStatus/pom.xml, samples/widgets/Subscriber/pom.xml, samples/widgets/TotalUpdates/pom.xml, samples/widgets/WidgetState/pom.xml, samples/widgets/pom.xml
> Update version into 4.0.0.beta-SNAPSHOT
=> Update version into 4.0.0.beta-SNAPSHOT

components/dashboards-web-component/src/listing/DashboardListing.jsx
> Fix sorting issue in dashboard lisitng page
Resolves #685
=> Fix sorting issue in dashboard lisitng page

components/dashboards-web-component/src/designer/DashboardDesigner.css, components/dashboards-web-component/src/designer/DashboardDesigner.jsx
Fixing https://github.com/wso2/carbon-dashboards/issues/688
=> Fixing carbon-dashboard issue-688

components/dashboards/org.wso2.carbon.dashboards.api/pom.xml, components/dashboards/org.wso2.carbon.dashboards.api/src/main/java/org/wso2/carbon/dashboards/api/internal/DashboardRestApi.java, components/dashboards/org.wso2.carbon.dashboards.api/src/main/java/org/wso2/carbon/dashboards/api/util/LogEncoder.java, components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/bean/DashboardMetadata.java, pom.xml
> Encode string before logging
> Add dependency for OWASP
> Encode strings that are being logged which may contain user inputs
=> Added owasp for encoding strings before logging

components/dashboards/org.wso2.carbon.dashboards.api/pom.xml, components/dashboards/org.wso2.carbon.dashboards.api/src/main/java/org/wso2/carbon/dashboards/api/internal/WidgetRestApi.java, components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/bean/widget/GeneratedWidgetConfigs.java, pom.xml
Fixes possible CRLF log attacks
Encode the output strings and avoid CRLF attacks
Using OWASP library to encode the Strings
=> Handling CRLF attacks

pom.xml
Reverting the version back to 4.0.0.beta3-SNAPSHOT
=> Change the version back to 4.0.0.beta3-SNAPSHOT

pom.xml
- $subject
- Also bumps MSF4j version to v2.4.2
=> Bump Carbon UI Server version to v0.14.1

components/dashboards-web-component/package-lock.json, components/dashboards-web-component/package.json, components/dashboards-web-component/public/locales/en.json, components/dashboards-web-component/public/locales/fr.json, components/dashboards-web-component/src/auth/SecuredRouter.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/components/ChartConfigurator.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/components/GadgetDetailsConfigurator.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/components/GadgetsGenerationWizard.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/components/ProviderConfigurator.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/components/chartPreview/ChartPreviewer.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/components/chartPropertyGenerators/main/Geographical.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/components/chartPropertyGenerators/main/LineAreaBar.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/components/chartPropertyGenerators/main/Number.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/components/chartPropertyGenerators/main/Pie.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/components/chartPropertyGenerators/main/Scatter.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/components/chartPropertyGenerators/main/TableChart.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/components/chartPropertyGenerators/sub/LineAreaBar.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/components/chartPropertyGenerators/sub/Scatter.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/components/inputTypes/ColorProperty.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/components/inputTypes/SelectProperty.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/components/inputTypes/StreamProperty.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/components/inputTypes/SwitchProperty.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/components/inputTypes/TextProperty.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/utils/Configurations.js, components/dashboards-web-component/src/gadgets-generation-wizard/utils/Constants.js, components/dashboards-web-component/src/gadgets-generation-wizard/utils/Types.js, components/dashboards-web-component/src/gadgets-generation-wizard/utils/UtilFunctions.js, components/dashboards-web-component/src/listing/DashboardListing.jsx, components/dashboards-web-component/src/utils/apis/GadgetsGenerationAPI.js
> Gadgets can be created and saved after selecting and configuring data provider and chart, from this wizard
=> Adding Gadgets Generation Wizard

components/dashboards/org.wso2.carbon.dashboards.api/src/main/java/org/wso2/carbon/dashboards/api/internal/DashboardRestApi.java
=> Changed LogEncoder Usage

components/dashboards/org.wso2.carbon.dashboards.core/src/test/java/org/wso2/carbon/dashboards/core/internal/DashboardMetadataProviderImplTest.java, components/dashboards/org.wso2.carbon.dashboards.core/src/test/java/org/wso2/carbon/dashboards/core/internal/MockPermissionProvider.java, pom.xml
>Incooperate common analytics changes to carbon-dashboards repo.
=> Incooperate common analytics changes

components/dashboards-web-component/src/viewer/DashboardView.jsx
This PR fixes the default text color in dashboard view mode depending on the selected theme.
=> Fix default text color in dashboard view mode

components/dashboards-web-component/src/auth/utils/AuthManager.jsx, components/dashboards-web-component/src/utils/apis/AuthenticationAPI.jsx
> Improve remember me functionality
=> Improve remember me functionality

base-widget/package.json, base-widget/src/Widget.jsx, samples/widgets/UserInfo/package.json, samples/widgets/UserInfo/src/UserInfo.jsx, samples/widgets/WidgetState/package.json, samples/widgets/WidgetState/src/WidgetState.jsx
This PR refactors the widget level APIs provided via the base widget.
Following APIs are exposed for widgets with this changeset.
```javascript
const state = super.getWidgetState(key)
```
```javascript
super.setWidgetState(key, state)
```
```javascript
const user = super.getCurrentUser()
```
Please refer **UserInfo** and **WidgetState** samples for implementation details.
=> Refactor base widget APIs

components/dashboards-web-component/package-lock.json, components/dashboards-web-component/src/designer/components/WidgetsList.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/components/GadgetsGenerationWizard.jsx, components/dashboards-web-component/src/utils/DashboardRenderingComponent.jsx, components/dashboards-web-component/src/utils/WidgetLoadingComponent.jsx, pom.xml, samples/widgets/UniversalWidget/package-lock.json, samples/widgets/pom.xml
> This PR will include necessary fixes for widget generation wizard and msf4j version upgrade.
=>  Improve functionality to work with generation wizard 

samples/widgets/sales-dashboard-widgets/CustomersByProduct/package.json, samples/widgets/sales-dashboard-widgets/CustomersByProduct/src/CustomersByProduct.jsx, samples/widgets/sales-dashboard-widgets/CustomersPerYear/package.json, samples/widgets/sales-dashboard-widgets/CustomersPerYear/src/CustomersPerYear.jsx, samples/widgets/sales-dashboard-widgets/OverallProductInfo/package.json, samples/widgets/sales-dashboard-widgets/OverallProductInfo/src/OverallProductInfo.jsx, samples/widgets/sales-dashboard-widgets/OverallRevenueInfo/package.json, samples/widgets/sales-dashboard-widgets/OverallRevenueInfo/src/OverallRevenueInfo.jsx, samples/widgets/sales-dashboard-widgets/RevenueByCountry/package.json, samples/widgets/sales-dashboard-widgets/RevenueByCountry/src/RevenueByCountry.jsx, samples/widgets/sales-dashboard-widgets/RevenueByProduct/package.json, samples/widgets/sales-dashboard-widgets/RevenueByProduct/src/RevenueByProduct.jsx, samples/widgets/sales-dashboard-widgets/RevenueByRegion/package.json, samples/widgets/sales-dashboard-widgets/RevenueByRegion/src/RevenueByRegion.jsx, samples/widgets/sales-dashboard-widgets/RevenuePerYear/package.json, samples/widgets/sales-dashboard-widgets/RevenuePerYear/src/RevenuePerYear.jsx, samples/widgets/sales-dashboard-widgets/RevenuePercentage/package.json, samples/widgets/sales-dashboard-widgets/RevenuePercentage/src/RevenuePercentage.jsx
This PR will fix the widget responsive issues of Sales Dashboard sample
=> Fixes for the responsive issues in sample widgets

components/dashboards-web-component/src/designer/components/PageEntry.jsx
=> Show a delete confirmation message when delete page is clicked in Dashboard Designer

components/dashboards-web-component/public/locales/en.json, components/dashboards-web-component/public/locales/fr.json, components/dashboards-web-component/src/designer/components/PageEntry.jsx
=> Changed the option Make as Homepage in dashboard designer to Mark as Homepage

components/dashboards-web-component/src/auth/utils/AuthManager.jsx
=> Removed hardcoded context path in deleteSessionCookie function of AuthManager.jsx

components/dashboards-web-component/src/auth/utils/AuthManager.jsx, samples/widgets/Publisher/src/Publisher.jsx, samples/widgets/Subscriber/src/Subscriber.jsx
=> Fixed the issue of displaying wrong time in Publisher and Subscriber sample widgets

components/dashboards-web-component/src/auth/utils/AuthManager.jsx, pom.xml
- This PR fixes names of renamed cookies.
- Bumps carbon.analytics version to v2.0.210
- Bumps carbon.analytics-common version to v6.0.42
=> Fix authentication changes

components/dashboards-web-component/pom.xml, components/dashboards/org.wso2.carbon.dashboards.api/pom.xml, components/dashboards/org.wso2.carbon.dashboards.core/pom.xml, features/org.wso2.carbon.dashboards.api.feature/pom.xml, features/org.wso2.carbon.dashboards.portal.feature/pom.xml, pom.xml, samples/components/org.wso2.carbon.dashboards.samples.endpoint/pom.xml, samples/features/org.wso2.carbon.dashboards.samples.feature/pom.xml, samples/pom.xml, samples/widgets/CpuUsage/pom.xml, samples/widgets/LoadAverage/pom.xml, samples/widgets/MemoryUsage/pom.xml, samples/widgets/Publisher/pom.xml, samples/widgets/ServerStatus/pom.xml, samples/widgets/Subscriber/pom.xml, samples/widgets/TotalUpdates/pom.xml, samples/widgets/UniversalWidget/pom.xml, samples/widgets/UserInfo/pom.xml, samples/widgets/WidgetState/pom.xml, samples/widgets/pom.xml, samples/widgets/sales-dashboard-widgets/CustomersByProduct/pom.xml, samples/widgets/sales-dashboard-widgets/CustomersPerYear/pom.xml, samples/widgets/sales-dashboard-widgets/OverallProductInfo/pom.xml, samples/widgets/sales-dashboard-widgets/OverallRevenueInfo/pom.xml, samples/widgets/sales-dashboard-widgets/RevenueByCountry/pom.xml, samples/widgets/sales-dashboard-widgets/RevenueByProduct/pom.xml, samples/widgets/sales-dashboard-widgets/RevenueByRegion/pom.xml, samples/widgets/sales-dashboard-widgets/RevenuePerYear/pom.xml, samples/widgets/sales-dashboard-widgets/RevenuePercentage/pom.xml
Next development iteration version in the repo was set to 4.0.0.beta5-SNAPSHOT after 4.0.0.beta5 release which is wrong. This PR will fix that issue.
=> Fix the next development iteration version

components/dashboards-web-component/src/viewer/Dashboard.css, components/dashboards-web-component/src/viewer/DashboardView.jsx
This PR introduces options to logout in dashboard viewer.
Resolves https://github.com/wso2/carbon-dashboards/issues/686
=> Add logout in dashboard view page

components/dashboards/org.wso2.carbon.dashboards.api/src/main/java/org/wso2/carbon/dashboards/api/internal/DashboardRestApi.java, components/dashboards/org.wso2.carbon.dashboards.api/src/main/java/org/wso2/carbon/dashboards/api/internal/WidgetRestApi.java
> Check if string is null before replacing CRLF characters
=> Null check for CRLF removed logs

components/dashboards-web-component/public/locales/en.json, components/dashboards-web-component/public/locales/fr.json, components/dashboards-web-component/src/designer/DashboardDesigner.jsx
Renames "Save" button to "Save Page" in dashboard designer.
=> Rename save button to save page

pom.xml
=> Update msf4j version

samples/widgets/UniversalWidget/src/UniversalWidget.jsx
=> Fixed auth header of UniversalWidget

samples/widgets/UniversalWidget/src/UniversalWidget.jsx
Fixing responsiveness of UniversalWidget
=> Fixing responsiveness of UniversalWidget

samples/widgets/CpuUsage/webpack.config.js, samples/widgets/LoadAverage/webpack.config.js, samples/widgets/MemoryUsage/webpack.config.js, samples/widgets/Publisher/webpack.config.js, samples/widgets/ServerStatus/webpack.config.js, samples/widgets/Subscriber/webpack.config.js, samples/widgets/TotalUpdates/webpack.config.js, samples/widgets/UniversalWidget/webpack.config.js, samples/widgets/UserInfo/webpack.config.js, samples/widgets/WidgetState/webpack.config.js, samples/widgets/sales-dashboard-widgets/CustomersByProduct/webpack.config.js, samples/widgets/sales-dashboard-widgets/CustomersPerYear/webpack.config.js, samples/widgets/sales-dashboard-widgets/OverallProductInfo/webpack.config.js, samples/widgets/sales-dashboard-widgets/OverallRevenueInfo/webpack.config.js, samples/widgets/sales-dashboard-widgets/RevenueByCountry/webpack.config.js, samples/widgets/sales-dashboard-widgets/RevenueByProduct/webpack.config.js, samples/widgets/sales-dashboard-widgets/RevenueByRegion/webpack.config.js, samples/widgets/sales-dashboard-widgets/RevenuePerYear/webpack.config.js, samples/widgets/sales-dashboard-widgets/RevenuePercentage/webpack.config.js
This PR remove source maps from sample widgets.
=> Remove source maps from sample widgets

components/dashboards/org.wso2.carbon.dashboards.api/src/main/java/org/wso2/carbon/dashboards/api/internal/WidgetRestApi.java
> Some issues in widget back end API are not properly bubbling up to frontend.
> Improve widget api logging and api error response for runtime issues.
=> Improve widget api logging and api error response for runtime issues.

samples/widgets/sales-dashboard-widgets/RevenueByCountry/src/RevenueByCountry.jsx
=> Fixed the styles of RevenueByCountry widget of the sample widgets

components/dashboards-web-component/package-lock.json, components/dashboards-web-component/src/gadgets-generation-wizard/components/GadgetsGenerationWizard.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/components/chartPropertyGenerators/main/GeographicalChart.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/components/chartPropertyGenerators/main/LineAreaBarChart.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/components/chartPropertyGenerators/main/NumberChart.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/components/chartPropertyGenerators/main/PieChart.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/components/chartPropertyGenerators/main/ScatterChart.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/components/chartPropertyGenerators/main/TableChart.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/components/chartPropertyGenerators/sub/LineAreaBarChart.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/components/chartPropertyGenerators/sub/ScatterChart.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/utils/Configurations.js, components/dashboards-web-component/src/gadgets-generation-wizard/utils/UtilFunctions.js
> - Modifying the configuration of a widget, used in saving to the database
> - Removing deprecated properties and adding new properties as required in new [chart configurations](https://docs.google.com/a/wso2.com/document/d/1kx7rqaJFn7mxXVQmuMULcyi8DWvoRv6tqMzTsUsdmIA/edit?usp=sharing)
> - Re-adding load configuration for a non-RDBMS provider, that was mistakenly removed while adding load default configuration for a RDBMS provider (in #797)
> #797
=> Widgets generation wizard - modifying configuration properties for charts

samples/widgets/Publisher/package.json, samples/widgets/Publisher/src/Publisher.jsx, samples/widgets/Subscriber/package.json, samples/widgets/Subscriber/src/Subscriber.jsx
Added material-ui elements to publisher and subscriber widgets.
Node.JS v.8.5.0, NPM v5.3.0
=> Fixed styles in Publisher and Subscriber Widgets

components/dashboards-web-component/src/auth/Login.jsx, components/dashboards-web-component/src/auth/SecuredRouter.jsx, components/dashboards-web-component/src/auth/utils/AuthManager.jsx, components/dashboards-web-component/src/utils/apis/AuthenticationAPI.jsx
This PR fixes issues in "remember me" functionality in "portal" application.
Resolves https://github.com/wso2/carbon-dashboards/issues/802
=> Fix login remember me functionality

samples/widgets/UserInfo/src/UserInfo.jsx, samples/widgets/sales-dashboard-widgets/RevenueByRegion/src/RevenueByRegion.jsx
=> Fixed styling issues of RevenueByCountry widget sample

components/dashboards/org.wso2.carbon.dashboards.api/pom.xml, components/dashboards/org.wso2.carbon.dashboards.core/pom.xml
Add missing commas OSGi import packaes and export packages in following bundles,
- org.wso2.carbon.dashboards.api
- org.wso2.carbon.dashboards.core
=> Add missing commas OSGi import packaes and export packages

components/dashboards-web-component/src/designer/DashboardDesigner.css
This style fix will fix the issue of appearing a scroll bar when both widget configuration panel and widget list panel in the designer view of the dashboards.
=> Fixed styles of Dashboard designer

components/dashboards-web-component/src/designer/components/PagesPanel.jsx
This PR fixes an issue in modifying page URL.
=> Fix issue in modifying page URL

samples/widgets/UserInfo/package.json
This PR updates the @wso2-dashboards/widget npm dependency in order to fix an issue in UserInfo widget.
=> Fix issue in UserInfo widget

components/dashboards-web-component/src/gadgets-generation-wizard/components/chartPropertyGenerators/main/GeographicalChart.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/components/chartPropertyGenerators/main/LineAreaBarChart.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/components/chartPropertyGenerators/sub/LineAreaBarChart.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/components/chartPropertyGenerators/sub/ScatterChart.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/utils/Constants.js
> - Modifying the chart configurations of Scatter chart & Geographical chart
> - Adding filters to `x` and `y` axis of Scatter chart
> - Renaming 'Independent axis' and 'Dependent axis' namely as 'X axis' and 'Y axis'
=> UI fixes & Minor chart configuration modifications

components/dashboards-web-component/src/designer/DashboardDesigner.jsx, components/dashboards-web-component/src/designer/DashboardSettings.jsx, components/dashboards-web-component/src/utils/DashboardUtils.jsx, components/dashboards-web-component/src/viewer/DashboardView.jsx
> Add proper 404 error pages in Dashboard component. This will introduce 404 error pages, when the user requests for dashboards and dashboards' pages which do not exist.
> Improve the user experience of the dashboard component.
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
Node - v8.8.1-linux-x64
=> Add proper error pages

components/dashboards-web-component/src/designer/DashboardDesigner.jsx
resolves #608 
Node.JS v8.5.0, NPM v5.3.0, JDK v1.8.0_144
=> Removing unwanted attributes from Dashboard JSON

components/dashboards-web-component/src/designer/DashboardCreatePage.jsx, components/dashboards-web-component/src/designer/DashboardDesigner.jsx, components/dashboards-web-component/src/designer/DashboardSettings.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/components/GadgetsGenerationWizard.jsx
resloves #751 
Node.JS v8.5.0, npm v5.3.0
[https://stackoverflow.com/questions/42701129/how-to-push-to-history-in-react-router-v4](https://stackoverflow.com/questions/42701129/how-to-push-to-history-in-react-router-v4)
=> Change window.location.href setters in API calls to handle through React Router

components/dashboards-web-component/src/viewer/DashboardView.jsx, components/dashboards-web-component/src/viewer/components/PageMenu.jsx, components/dashboards-web-component/src/viewer/components/Sidebar.jsx
> Highlight the selected page in dashboard view
> NA
> NA
> NA
> NA
> NA
> NA
> NA
> NA
> NA
> NA
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
Node - v8.8.1-linux-x64
> NA
=> Highlight the selected page in dashboard view

components/dashboards-web-component/src/designer/components/PagesPanel.jsx
resolves #751 
Node.JS v8.9.4, NPM v5.6.0
=> Removed the remaining window.location.href setters

components/dashboards-web-component/public/locales/en.json, components/dashboards-web-component/public/locales/fr.json, components/dashboards-web-component/src/designer/DashboardDesigner.jsx, components/dashboards-web-component/src/designer/DashboardSettings.jsx, components/dashboards-web-component/src/error-pages/Error403.jsx, components/dashboards-web-component/src/listing/DashboardListing.jsx, components/dashboards-web-component/src/utils/Constants.jsx, components/dashboards-web-component/src/viewer/DashboardView.jsx, components/dashboards/org.wso2.carbon.dashboards.api/src/main/java/org/wso2/carbon/dashboards/api/internal/DashboardRestApi.java
This PR will provides following fixes,
- Fix login issue in portal after restarting the server
- Refactor the error pages using proper HTTP codes.
Resolves https://github.com/wso2/product-sp/issues/457
Fix dashboard portal login issues after restarting the server
Check the 403 HTTP code of API call responses and redirect to login page according to that.
NA
NA
NA
NA
NA
NA
NA
NA
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
npm …
=> Fix login issue in portal after restarting the server

components/dashboards-web-component/src/designer/components/PagesPanel.jsx
Fix page loading issue in designer view
Resolves #849 
Fix page loading issue in designer view
Pass the correct parameters to build pages method.
NA
NA
NA
NA
NA
NA
NA
NA
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
NPM 5.4.2
NA
=> Fix page loading issue in designer view

components/universal-widget/pom.xml
Updating component version of Universal Widget
Node.JS v8.8.1, NPM v5.4.2
=> updating the component version of universal widget

components/universal-widget/pom.xml
Updating parent version of the Universal Widget Component
Node.JS v8.8.1, NPM v5.4.2
=> Updating parent version of the Universal Widget Component

apps/portal/extensions/authentication/basic-login.jag, apps/portal/extensions/locales/locale_default.json, apps/portal/extensions/locales/locale_si.json, apps/portal/theme/templates/login.jag
This PR adds cookie policy in the login page to comply with GDPR.
=> Add cookie policy message in login pages

components/dashboards-web-component/public/locales/en.json, components/dashboards-web-component/public/locales/fr.json, components/dashboards-web-component/src/auth/Login.jsx
This PR adds cookie policy in the login page to comply with GDPR.
=> Add cookie policy in login page

components/shindig-server/pom.xml, components/shindig-wso2-extensions/pom.xml, pom.xml
> Update shindig version to the forked version
=> Update shindig version

components/dashboards-web-component/src/auth/Login.jsx
Fixes https://github.com/wso2/product-sp/issues/505
$subject.
=> Correct cookie policy URL and privacy policy URL in the login page

apps/portal/css/login.css
Fixing policies link prominence https://github.com/wso2/product-das/issues/310
=> Fixing policies link prominency 

pom.xml
=> Upgrade shindig version

apps/portal/extensions/authentication/basic-logout.jag
This PR improve sanitization of "destination" request parameter in basic-logout in `portal/extensions/authentication/basic-logout.jag` file.
- Unit tests 
N/A
N/A
#871 for 2.0.x
=> Improve sanitization of "destination" request parameter in basic-logout

components/dashboards-web-component/src/auth/Login.jsx
=> Add autoFocus attribute to the username field in the login page

components/dashboards-web-component/src/common/components/Header.jsx
Fixes #878 
Logo & the title should be link to the homa page (`/portal/`)
=> Link logo and title to home page

components/dashboards-web-component/src/designer/DashboardDesigner.jsx
Fix scroll-bar issue in widgets panel
Fix scroll-bar issue in widgets panel
Fix scroll-bar issue in widgets panel
NA
NA
NA
NA
NA
NA
NA
NA
NA
=> Fix scroll-bar issue in widgets panel

components/dashboards-web-component/src/viewer/DashboardViewPage.jsx
Add material ui color palette and formatting.
Resolves #894
=> Add material ui color palette and formatting

samples/features/org.wso2.carbon.dashboards.samples.feature/pom.xml, samples/widgets/DateTimeRangePicker/package-lock.json, samples/widgets/DateTimeRangePicker/package.json, samples/widgets/DateTimeRangePicker/pom.xml, samples/widgets/DateTimeRangePicker/src/CustomTimeRangeSelector.jsx, samples/widgets/DateTimeRangePicker/src/DateRangePicker.jsx, samples/widgets/DateTimeRangePicker/src/DateTimePicker.jsx, samples/widgets/DateTimeRangePicker/src/GranularityModeSelector.jsx, samples/widgets/DateTimeRangePicker/src/resources/widgetConf.json, samples/widgets/DateTimeRangePicker/src/styles/main.css, samples/widgets/DateTimeRangePicker/webpack.config.js, samples/widgets/pom.xml
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
=> Add DateTimeRangePicker sample widget

pom.xml
=> Fixing build by adding date-time-range picker widget dependency

components/dashboards-web-component/src/designer/components/WidgetConfigurationPane.jsx, components/universal-widget/package-lock.json, components/universal-widget/package.json
Upgrade base widget version in the universal widget
Upgrade base widget version in the universal widget
Upgrade base widget version in the universal widget
NA
NA
NA
NA
NA
NA
NA
NA
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
NA
=> Upgrade base widget version in universal widget

samples/widgets/DateTimeRangePicker/package-lock.json, samples/widgets/DateTimeRangePicker/package.json
Fix build issue in DateTimeRange picker
Fix build issue in DateTimeRange picker
Fix build issue in DateTimeRange picker
=> Fix build issue in DateTimeRange picker

components/dashboards-web-component/src/designer/DashboardDesignerPage.jsx, components/dashboards-web-component/src/designer/components/DashboardRenderer.jsx, components/dashboards-web-component/src/designer/components/WidgetConfigurationPane.jsx, components/dashboards-web-component/src/utils/GoldenLayoutContentUtils.js
$subject.
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type …
=> Fix cannot open widget configurations panel in sales dashboard designer

components/dashboards-web-component/src/utils/WidgetClassRegistry.js, samples/widgets/Publisher/src/Publisher.jsx, samples/widgets/Subscriber/src/Subscriber.jsx
A dashboard designed with sample Publisher, Subscriber widgets doesn't wire pub-sub correctly. This Pr fixes that.
> Link to the …
=> Fix sample Publisher, Subscriber widgets

components/dashboards-web-component/src/designer/components/WidgetConfigurationPane.jsx, components/dashboards-web-component/src/utils/GoldenLayoutContentUtils.js
Cannot open the widget configuration panel in the designer of Twitter Analytics dashboard. This PR fixes that issue.
> Link to …
=> Gracefully access pub-sub config from a widget configuration.

base-widget/package-lock.json, base-widget/package.json
Bump version of base-widget to v1.1.2
Node.JS v8.8.1, NPM v5.4.2
=> Bump version of base-widget to v1.1.2

components/dashboards-web-component/src/common/WidgetRenderer.jsx, components/dashboards-web-component/src/designer/components/DashboardRenderer.jsx, components/dashboards-web-component/src/designer/components/WidgetConfigurationPane.jsx, components/dashboards-web-component/src/designer/components/WidgetPubSubConfig.jsx, components/dashboards-web-component/src/utils/GoldenLayoutContentUtils.js, components/universal-widget/src/UniversalWidget.jsx
This PR fixes issues found in the pub-sub configurations handling, rendering, and saving in the Widget Configurations pane in the dashboard designer.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why …
=> Fix handling, rendering, and saving pub-sub related configurations.

components/dashboards-web-component/src/designer/components/DashboardRenderer.jsx, components/dashboards-web-component/src/designer/components/WidgetConfigurationPane.jsx, components/dashboards-web-component/src/designer/components/WidgetPubSubConfig.jsx, components/dashboards-web-component/src/utils/GoldenLayoutContentUtils.js
$subject
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type …
=> Fix not showing pub-sub configuration in the widget configuration panel in the Sales Dashboard

components/dashboards-web-component/src/designer/components/WidgetConfigurationPane.jsx, components/dashboards-web-component/src/designer/components/WidgetOptionsConfiguration.jsx, components/dashboards-web-component/src/designer/components/WidgetPubSubConfiguration.jsx
$subject.
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type …
=> Add component for rendering widget options in widget configuration pane in designer

components/dashboards-web-component/src/designer/components/DashboardRenderer.jsx, components/dashboards-web-component/src/designer/components/WidgetPubSubConfiguration.jsx
$subject. Settings button should be display if only the relevant widget is a subscriber and has options.
> Link to the PR for …
=> Fix displaying settings buttons for all widgets in the designer

components/dashboards-web-component/package.json, components/dashboards-web-component/public/locales/en.json, components/dashboards-web-component/public/locales/fr.json, components/dashboards-web-component/src/designer/components/DashboardRenderer.jsx, components/dashboards-web-component/src/designer/components/WidgetOptionsConfiguration.jsx, components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/bean/widget/Option.java
Add widget options support - user preferences 
Add widget options support - user preferences 
Add widget options support - user preferences 
NA
NA
NA
NA
NA
NA
NA
NA
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
NPM 5.4.2
NA
=>  Add widget options support - user preferences 

components/dashboards-web-component/package.json, components/dashboards-web-component/src/designer/DashboardCreatePage.jsx, components/dashboards-web-component/src/designer/components/DashboardRenderer.jsx, components/dashboards-web-component/src/utils/DashboardUtils.jsx, components/dashboards-web-component/src/utils/GoldenLayoutContentUtils.js, components/dashboards-web-component/src/utils/Theme.js, components/dashboards-web-component/src/utils/WidgetClassRegistry.js, components/dashboards-web-component/src/utils/apis/AuthenticationAPI.jsx
=> Remove unused function in classes in src/utils

components/dashboards-web-component/package-lock.json, components/dashboards-web-component/package.json, components/dashboards-web-component/src/gadgets-generation-wizard/components/ChartConfigurator.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/components/chartPreview/ChartPreviewer.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/components/chartPreview/PreviewerWidget.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/components/chartPropertyGenerators/main/TableChart.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/utils/Configurations.js, components/dashboards-web-component/src/gadgets-generation-wizard/utils/UtilFunctions.js
Fix Table Chart generation of Chart Generation Wizard
NPM v5.4.2, Node.JS v8.8.1
=> Fix Table Chart generation of Chart Generation Wizard

components/dashboards-web-component/src/common/WidgetRenderer.jsx, components/dashboards-web-component/src/designer/components/DashboardRenderer.jsx, components/dashboards-web-component/src/designer/components/WidgetOptionsConfiguration.jsx, samples/widgets/sales-dashboard-widgets/RevenueByProductWithUserPreferences/src/RevenueByProductWithUserPreferences.jsx, samples/widgets/sales-dashboard-widgets/RevenueByProductWithUserPreferences/src/resources/widgetConf.json
Fix issues in user-pref sample widget
Fix dropping widgets with the same id
Fix issues in user-pref sample widget
Fix dropping widgets with the same id
Fix issues in user-pref sample widget
Fix dropping widgets with the same id
NA
NA
NA
NA
NA
NA
NA
NA
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
NPM 5.4.2
NA
=> Fix issues in designer & user-pref sample

components/dashboards-web-component/src/viewer/DashboardViewPage.jsx
=> Fix app bar in dashboard view page.

samples/widgets/DateTimeRangePicker/package-lock.json, samples/widgets/DateTimeRangePicker/package.json, samples/widgets/DateTimeRangePicker/src/CustomTimeRangeSelector.jsx, samples/widgets/DateTimeRangePicker/src/DateRangePicker.jsx, samples/widgets/DateTimeRangePicker/src/DateTimePicker.jsx, samples/widgets/DateTimeRangePicker/src/GranularityModeSelector.jsx
=> Change mui versions to 1.0.0.beta-43 to solve select window not rendering properly issue

components/dashboards-web-component/src/common/WidgetRenderer.jsx
=> Use commonly defined theme in WidgetRenderer

components/dashboards-web-component/package-lock.json, components/dashboards-web-component/package.json, components/dashboards-web-component/src/gadgets-generation-wizard/components/GadgetsGenerationWizard.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/components/ProviderConfigurator.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/components/ProviderConfiguratorComponents/MetaDataCollector.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/components/chartPropertyGenerators/main/TableChart.jsx, components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/bean/widget/GeneratedWidgetConfigs.java, components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/bean/widget/WidgetConfigs.java, components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/WidgetMetadataProviderImpl.java, components/universal-widget/package-lock.json, components/universal-widget/package.json, components/universal-widget/src/UniversalWidget.jsx
Add WebsocketProvider support for Chart Generation Wizard
NPM v5.4.2, Node.JS v8.8.1
=> Add WebsocketProvider support for Chart Generation Wizard

samples/widgets/DateTimeRangePicker/src/DateRangePicker.jsx
$subject (Fixes https://github.com/wso2/carbon-dashboards/issues/938)
=>  Changing DateRangePicker styling based on theme selected in dashboard

base-widget/.gitignore, base-widget/package-lock.json, base-widget/package.json, base-widget/src/Widget.jsx, samples/widgets/Publisher/src/Publisher.jsx
=> Fix subscribe method in the base widget class

samples/features/org.wso2.carbon.dashboards.samples.feature/pom.xml
Remove unused widgets from the sample feature
=> Remove unused widgets from the sample feature

components/dashboards-web-component/package-lock.json, components/dashboards-web-component/package.json, components/dashboards-web-component/src/common/WidgetRenderer.jsx, components/dashboards-web-component/src/utils/WidgetClassRegistry.js
=> Use base Widget class in WidgetClassRegistry class to check version & patch subscribe method.

base-widget/package-lock.json, base-widget/package.json
Bump version of base-widget to v1.2.1 to publish it with the changes of #948
=> Bump version of base-widget to v1.2.1

components/dashboards-web-component/src/common/WidgetRenderer.jsx, components/universal-widget/src/UniversalWidget.jsx
=> Remove unwanted console logs

components/dashboards-web-component/src/designer/components/WidgetPubSubConfiguration.jsx, components/universal-widget/src/UniversalWidget.jsx
Improve the widget generation and designer
Improve the widget generation and designer
=> Improve the widget generation and designer

components/dashboards-web-component/src/viewer/DashboardViewPage.jsx
=> Allow dashboard to save the current Theme in localStorage

components/dashboards-web-component/src/designer/components/WidgetPubSubConfiguration.jsx
=> Fix widgetpubsub panel issue

samples/widgets/Publisher/src/Publisher.jsx, samples/widgets/Subscriber/src/Subscriber.jsx
=> Fixes clear button not working in Publisher, Subscriber widgets

components/dashboards-web-component/public/locales/en.json, components/dashboards-web-component/public/locales/fr.json, components/dashboards-web-component/src/designer/components/LeftSidePane.jsx, components/dashboards-web-component/src/designer/components/PagesSidePane.jsx, components/dashboards-web-component/src/designer/components/WidgetsSidePane.jsx
Adding headers to left-side panel
=> Adding headers to left-side panel

components/dashboards-web-component/src/gadgets-generation-wizard/components/GadgetsGenerationWizard.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/components/ProviderConfigurator.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/components/inputTypes/ColorProperty.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/components/inputTypes/SelectProperty.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/components/inputTypes/StreamProperty.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/components/inputTypes/TextProperty.jsx
Provide inline hints in widget generation wizard
Provide inline hints in widget generation wizard
=> Provide inline hints in widget generation wizard

components/dashboards-web-component/public/locales/en.json, components/dashboards-web-component/public/locales/fr.json, components/dashboards-web-component/src/listing/DashboardListingPage.jsx, components/dashboards-web-component/src/listing/components/DashboardCard.jsx
This PR fixes the following issues in dashboard listing page.
- Reduced the dashboard card font size 
- Fix dashboards not available message when fetching dashboards.
=> Fix dashboard listing page

components/dashboards/org.wso2.carbon.dashboards.core/src/test/java/org/wso2/carbon/dashboards/core/internal/DashboardMetadataProviderImplTest.java
=> Fix RoleID in DashboardMetadataProviderImplTest

components/universal-widget/src/UniversalWidget.jsx
In the widget generation wizard, when there are multiple input parameters defined, all the inputs other than the first takes the default value. This PR fixes this issue.
=> Fix issue in multiple input handling in widget generation wizard

pom.xml
This PR bumps analytics dependency versions.
=> Bump analytics dependency versions

components/dashboards-web-component/src/designer/DashboardDesignerPage.jsx, components/dashboards-web-component/src/viewer/DashboardViewPage.jsx
Fixing following issue
- Viewer
- Designer
After fix:
- Viewer
- Designer
- Unit tests 
N/A
N/A
=> Fix always scrollbars visible issue in dashboard designer & viewer

base-widget/package-lock.json, base-widget/package.json
$subject.
- Unit tests 
N/A
N/A
- Node v8.8.1
- NPM v5.4.2
=> Preparing for base widget v1.3.0 release

components/dashboards-web-component/package-lock.json, components/dashboards-web-component/package.json, components/dashboards-web-component/src/utils/WidgetClassRegistry.js, components/universal-widget/package-lock.json, components/universal-widget/package.json
$subject.
- Unit tests 
N/A
N/A
- Node v8.8.1
- NPM v5.4.2
=> Bump base widget dependency in dashboard web component & universal widget to v1.3.0

pom.xml
Bump versions of carbon-analytics-common and carbon-analytics.
=> Bump versions of analytics repos.

components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/bean/DashboardConfigurations.java, components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/DashboardMetadataProviderImpl.java, components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/database/DashboardMetadataDaoFactory.java, components/dashboards/org.wso2.carbon.dashboards.core/src/test/java/org/wso2/carbon/dashboards/core/internal/database/DashboardMetadataDaoFactoryTest.java
$subject
- Unit tests 
Passes current tests
N/A
=> Fix loading configurations from deployment.yaml multiple times

components/universal-widget/src/UniversalWidget.jsx
Fix issue in universal widget with pubsub message queuing
Fix issue in universal widget with pubsub message queuing
Fix issue in universal widget with pubsub message queuing
NA
NA
NA
NA
NA
NA
NA
NA
NA
NA
=> Fix issue in universal widget with pubsub message queuing

base-widget/src/Widget.jsx, samples/widgets/WidgetState/src/WidgetState.jsx
This PR fixes widget state API which tried to JSON parse a URI Encoded string.
=> Fix widget state API

base-widget/package-lock.json, base-widget/package.json, base-widget/src/Widget.jsx
$subject.
- Node v8.8.1
- NPM v5.4.2
=> Bump base widget version to 1.4.0 version

components/dashboards-web-component/src/designer/components/WidgetPubSubConfiguration.jsx
Fix issue in widget config panel when there is no pusbub config
Fix issue in widget config panel when there is no pusbub config
Fix issue in widget config panel when there is no pusbub config
NA
NA
NA
NA
NA
NA
NA
NA
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
Node v8.8.1
NPM 5.4.2
NA
=> Fix issue in widget config panel when there is no pusbub config

pom.xml
=> Bump depencies.

components/dashboards-web-component/src/designer/components/DashboardRenderer.jsx, components/dashboards-web-component/src/utils/Constants.jsx, components/dashboards-web-component/src/utils/GoldenLayoutFactory.js
Fixes #1006 
- Unit tests 
N/A
N/A
- Node v8.8.1
- NPM v5.4.2
=> Fix removing last widget of a dashboard page not getting saved

components/universal-widget/package-lock.json, components/universal-widget/package.json
$subject
- Node v8.8.1
- NPM v5.4.2
=> Bump VizG version to v0.7.29 in the universal widget

pom.xml
=> Bump carbon-analytics-common version to v6.0.68

components/dashboards-web-component/src/utils/GoldenLayoutContentUtils.js, components/dashboards-web-component/src/viewer/DashboardViewPage.jsx, components/dashboards-web-component/src/viewer/components/DashboardRenderer.jsx
$subject.
- Node v8.8.1
- NPM v5.4.2
=> Fix multiple rendering of GL when resize in dashboard viewer

components/dashboards-web-component/src/utils/DashboardReportGenerator.js, components/dashboards-web-component/src/viewer/components/DashboardRenderer.jsx, components/dashboards-web-component/src/viewer/components/DashboardReportGenerationCard.jsx
To fix identified bugs.
Fix currentPage name bug.
Handle widget report generation error.
Fix report generation button padding issue.
=> Fix dashboard report generation feature bugs

components/dashboards-web-component/src/designer/components/WidgetsSidePane.jsx
This will help in identifying the cause for widget pane loading fail
=> Log error when widget pane loading fail

components/dashboards-web-component/src/viewer/components/DashboardRenderer.jsx
This fixes the issue in rendering page height in dashboard viewer.
=> Fix dashboard viewer height issue

components/dashboards-web-component/src/viewer/components/DashboardRenderer.jsx
This PR fixes the dashboard viewer height when the height is not defined.
=> Fix default dashboard height

components/dashboards-web-component/public/css/dashboard.css, components/dashboards-web-component/src/App.jsx
World map is hidden in Sales Dashboard. This PR fixes that issue.
=> Fix world map hidden issue in Sales dashboard

apps/portal/controllers/includes/dashboard-scripts.jag
Implement encoding in dashboard description field in the settings page
Implement encoding in dashboard description field in the settings page
Implement encoding in dashboard description field in the settings page
NA
NA
NA
NA
NA
NA
NA
NA
NA
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
NA
=> Implement encoding in dashboard description field in settings page

components/dashboards/org.wso2.carbon.dashboards.api/src/main/java/org/wso2/carbon/dashboards/api/internal/WidgetRestApi.java
> To fix the deletion of widgets generated through widget generation wizard
>Fix bugs
=> Fix deletion of generated widgets.

components/dashboards-web-component/src/viewer/DashboardViewPage.jsx, components/dashboards-web-component/src/viewer/components/side-bar-nav-styles.css
=> Fix home icon styles

components/dashboards-web-component/src/gadgets-generation-wizard/components/ChartConfigurator.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/components/DynamicQueryComponent.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/components/GadgetsGenerationWizard.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/components/ProviderConfigurator.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/components/chartPropertyGenerators/main/LineAreaBarChart.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/components/chartPropertyGenerators/sub/LineAreaBarChart.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/components/chartPropertyGenerators/sub/ScatterChart.jsx, components/dashboards-web-component/src/gadgets-generation-wizard/utils/Configurations.js, components/dashboards-web-component/src/gadgets-generation-wizard/utils/UtilFunctions.js
Improve widget generation wizard
- Add front end validation and improve error messages
- Add sample values for data providers
Improve widget generation wizard
- Add front end validation and improve error messages
- Add sample values for data providers
Improve widget generation wizard
- Add front end validation and improve error messages
- Add sample values for data providers
NA
NA
NA
NA
NA
NA
NA
NA
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build …
=> Improve widget generation wizard

pom.xml
=> Bump carbon-analytics version

pom.xml
Bump Carbon Analytics version.
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? N/A
- Ran FindSecurityBugs plugin and verified report? N/A
=> Bump Carbon Analytics version.

pom.xml
This newer shindig version has upgraded commons-fileupload version
=> Upgrade shindig version.

README.md, pom.xml
=> Bump dependency

components/dashboards-web-component/src/utils/WidgetChannelManager.js
> Implement Data Provider poll method in widgetChannelManager
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
> https://github.com/wso2/carbon-analytics/pull/1552
=> Data provider poll method dashboard implementation

components/dashboards/org.wso2.carbon.dashboards.siddhi.apps.api/pom.xml
=> Bump siddhi apps api version to the latest

pom.xml
=> Bump analytics version

components/universal-widget/babel.config.js, components/universal-widget/package-lock.json, components/universal-widget/package.json, components/universal-widget/webpack.config.js
$subject.
- Unit tests 
N/A
N/A
=> Upgrade Babel to v7 & Webpack to v4 in the Univeral Widget

components/dashboards/org.wso2.carbon.dashboards.siddhi.apps.api/src/main/java/org/wso2/carbon/siddhi/apps/api/rest/impl/SiddhiAppsApiServiceImpl.java
>Fixes #1132 
- Ran FindSecurityBugs plugin and verified report? yes/no
=> [Data Search] Add a log if no workers are configured for Data Search Feature 

components/universal-widget/package.json, samples/widgets/sales-dashboard-widgets/CustomersByProduct/package.json, samples/widgets/sales-dashboard-widgets/CustomersByProduct/src/CustomersByProduct.jsx, samples/widgets/sales-dashboard-widgets/CustomersPerYear/package.json, samples/widgets/sales-dashboard-widgets/OverallProductInfo/package.json, samples/widgets/sales-dashboard-widgets/OverallProductInfo/src/OverallProductInfo.jsx, samples/widgets/sales-dashboard-widgets/OverallRevenueInfo/package.json, samples/widgets/sales-dashboard-widgets/OverallRevenueInfo/src/OverallRevenueInfo.jsx, samples/widgets/sales-dashboard-widgets/RevenueByCountry/package.json, samples/widgets/sales-dashboard-widgets/RevenueByCountry/src/RevenueByCountry.jsx, samples/widgets/sales-dashboard-widgets/RevenueByProduct/package.json, samples/widgets/sales-dashboard-widgets/RevenueByProduct/src/RevenueByProduct.jsx, samples/widgets/sales-dashboard-widgets/RevenueByRegion/package.json, samples/widgets/sales-dashboard-widgets/RevenueByRegion/src/RevenueByRegion.jsx, samples/widgets/sales-dashboard-widgets/RevenuePerYear/package.json, samples/widgets/sales-dashboard-widgets/RevenuePercentage/package.json, samples/widgets/sales-dashboard-widgets/RevenuePercentage/src/RevenuePercentage.jsx
Bump React-VizGrammar to latest version V0.8.4 in Sales Dashboard
=> Bump React-VizGrammar to latest version V0.8.4 in Sales Dashboard

components/universal-widget/src/UniversalWidget.jsx
> Fix https://github.com/wso2/product-ei/issues/3336
> Fix #1146 
=> [UniversalWidget] Set timeFormat according to the granularity

components/dashboards-web-component/src/utils/apis/AuthenticationAPI.jsx, components/dashboards-web-component/src/utils/apis/DashboardAPI.jsx, components/dashboards-web-component/src/utils/apis/GadgetsGenerationAPI.js, components/dashboards-web-component/src/utils/apis/WidgetAPI.jsx
$subject, as 2-second timeout is far too low
N/A
=> Increase API invocation timeouts

components/dashboards-web-component/src/auth/Login.jsx
=> Fix referrer redirection issue while login

pom.xml
=> Update carbon-dashboards dependency

components/dashboards-web-component/src/auth/Constants.jsx, components/dashboards-web-component/src/auth/Login.jsx, components/dashboards-web-component/src/auth/utils/AuthManager.jsx, components/dashboards-web-component/src/utils/apis/AuthenticationAPI.jsx
=> Fix logout failure after refreshing session

pom.xml
=> Update carbon-dashboards dependencies

components/shindig-server/src/main/resources/shindig.properties, components/shindig-server/src/main/resources/web.xml, pom.xml
Revert https://github.com/wso2/carbon-dashboards/pull/1095 and add properties needed for https://github.com/wso2/wso2-shindig/pull/15
Note: Please merge after https://github.com/wso2/wso2-shindig/pull/15
=> Revert #1095 and add properties needed for wso2/wso2-shindig#15

components/dashboards/org.wso2.carbon.dashboards.siddhi.apps.api/pom.xml, components/dashboards/org.wso2.carbon.dashboards.siddhi.apps.api/src/main/java/org/wso2/carbon/siddhi/apps/api/rest/bean/SiddhiStoreElement.java, components/dashboards/org.wso2.carbon.dashboards.siddhi.apps.api/src/main/java/org/wso2/carbon/siddhi/apps/api/rest/impl/SiddhiAppsApiServiceImpl.java, pom.xml
=> Bump siddhi version to 5.1.1

components/dashboards/org.wso2.carbon.dashboards.siddhi.apps.api/pom.xml, pom.xml
This PR fixes #1170 
openjdk64-1.8.0.212
MacOS Mojave 10.14.6
Google Chrome 64 bit Version 76.0.3809.100
=> Fix issue #1170 and update dependency versions

components/shindig-server/src/main/resources/web.xml, pom.xml
> Update shindig version and skip annotation scanning during startup
=> Update shindig version and skip annotation scanning during startup

components/dashboards-web-component/src/auth/utils/AuthManager.jsx, pom.xml
Add scopes to the redirection url
=> Add scopes to the redirection url

components/dashboards-web-component/src/common/WidgetRenderer.jsx, components/dashboards-web-component/src/utils/GoldenLayoutFactory.js, components/dashboards-web-component/src/utils/WidgetChannelManager.js, components/dashboards/org.wso2.carbon.dashboards.core/pom.xml, components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/DashboardDataProviderAuthorizer.java, components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/DashboardMetadataProviderImpl.java, components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/utils/DashboardUtil.java, components/universal-widget/src/UniversalWidget.jsx, pom.xml
Add DashboardDataProviderAuthorizer to secure widget web-socket communication.
Secure data provider WebSockets.
=> Add DashboardDataProviderAuthorizer to secure widget web-socket communication

components/dashboards-web-component/pom.xml, components/dashboards/org.wso2.carbon.dashboards.api/pom.xml, components/dashboards/org.wso2.carbon.dashboards.core/pom.xml, components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/DashboardDataProviderAuthorizer.java, components/dashboards/org.wso2.carbon.dashboards.siddhi.apps.api/pom.xml, components/universal-widget/pom.xml, features/org.wso2.carbon.dashboards.api.feature/pom.xml, features/org.wso2.carbon.dashboards.portal.feature/pom.xml, pom.xml, samples/features/org.wso2.carbon.dashboards.samples.feature/pom.xml, samples/pom.xml, samples/widgets/Publisher/pom.xml, samples/widgets/Subscriber/pom.xml, samples/widgets/UserInfo/pom.xml, samples/widgets/WidgetState/pom.xml, samples/widgets/pom.xml, samples/widgets/sales-dashboard-widgets/CustomersByProduct/pom.xml, samples/widgets/sales-dashboard-widgets/CustomersPerYear/pom.xml, samples/widgets/sales-dashboard-widgets/OverallProductInfo/pom.xml, samples/widgets/sales-dashboard-widgets/OverallRevenueInfo/pom.xml, samples/widgets/sales-dashboard-widgets/RevenueByCountry/pom.xml, samples/widgets/sales-dashboard-widgets/RevenueByProduct/pom.xml, samples/widgets/sales-dashboard-widgets/RevenueByProductWithUserPreferences/pom.xml, samples/widgets/sales-dashboard-widgets/RevenueByRegion/pom.xml, samples/widgets/sales-dashboard-widgets/RevenuePerYear/pom.xml, samples/widgets/sales-dashboard-widgets/RevenuePercentage/pom.xml
Updated snapshot version to 4.1.0 to address major siddhi and carbon analytics version change.
This PR also adds the ability to replace context path, tenant name, tenant id in the query if values are given.
=> Update snapshot version to 4.1.0 and add other improvements

components/shindig-server/src/main/resources/shindig.properties
> - Allow enable or disable the property for the allowed URL whitelist feature.
> - Depends on https://github.com/wso2/wso2-shindig/pull/20
=> Add allowed URL whitelist feature enable property

components/dashboards/org.wso2.carbon.dashboards.api/src/main/java/org/wso2/carbon/dashboards/api/internal/DashboardRestApi.java, components/dashboards/org.wso2.carbon.dashboards.core/pom.xml, components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/DashboardDataProviderAuthorizer.java, components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/DashboardMetadataProvider.java, components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/bean/authorizer/TenantIdInfo.java, components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/DashboardImporter.java, components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/DashboardMetadataProviderImpl.java, components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/authorizer/DashboardAuthorizerServiceFactory.java, components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/authorizer/DashboardAuthorizerServiceStub.java, components/dashboards/org.wso2.carbon.dashboards.core/src/test/java/org/wso2/carbon/dashboards/core/internal/MockPermissionProvider.java, pom.xml
This PR adds ability to Get `tenantId` by calling to the admin rest api and get roles specific to the tenant.
This also updates the dependency versions of carbon-analytics and carbon-analytics-common.
=> Add tenant related improvements

components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/DashboardDataProviderAuthorizer.java
Change admin username and password key constants
=> Change admin username and password key constants

components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/DashboardDataProviderAuthorizer.java
Add CONTEXT_CONTAINS_CONDITION_KEY and replace values
=> Add CONTEXT_CONTAINS_CONDITION_KEY and replace values

components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/database/DashboardMetadataDao.java, components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/database/WidgetMetadataDao.java, components/dashboards/org.wso2.carbon.dashboards.core/src/test/java/org/wso2/carbon/dashboards/core/internal/database/DashboardMetadataDaoTest.java, components/dashboards/org.wso2.carbon.dashboards.core/src/test/java/org/wso2/carbon/dashboards/core/internal/database/WidgetMetadataDaoTest.java
This PR fixes https://github.com/wso2/analytics-apim/issues/759 issue. 
Fix bugs
Mac OS Catalina, Postgres 11.5
=> Fix https://github.com/wso2/analytics-apim/issues/759

components/dashboards-web-component/src/auth/Login.jsx, components/dashboards-web-component/src/auth/SecuredRouter.jsx, components/dashboards-web-component/src/auth/utils/AuthManager.jsx
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
=> Handle error on token refresh

components/dashboards-web-component/src/gadgets-generation-wizard/components/GadgetsGenerationWizard.jsx, components/dashboards-web-component/src/utils/apis/DashboardAPI.jsx, components/dashboards-web-component/src/widget-store/WidgetStore.jsx, components/dashboards/org.wso2.carbon.dashboards.api/src/main/java/org/wso2/carbon/dashboards/api/internal/DashboardRestApi.java, components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/DashboardMetadataProvider.java, components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/bean/roles/provider/Roles.java, components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/DashboardMetadataProviderImpl.java, components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/roles/provider/RolesProvider.java
This PR fixes https://github.com/wso2/analytics-apim/issues/810 and also addresses https://github.com/wso2/analytics-apim/issues/800 and https://github.com/wso2/analytics-apim/issues/799 issues.
With this PR a new permission is introduced for widget creation. In order to enable widget generation wizard the **widgetCreators** section should be included in the dashboard deployment.yaml file with the list of scopes the permission is granted.
```
wso2.dashboard:
roles:
creators:
- apim_analytics:admin_carbon.super
widgetCreators:
- apim_analytics:admin_carbon.super
```
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email …
=> Disable gadget generation wizard by default and add widget creator permission

components/dashboards-web-component/src/auth/SecuredRouter.jsx, components/dashboards-web-component/src/auth/utils/AuthManager.jsx
This PR fixes https://github.com/wso2/analytics-apim/issues/851 issue by updating the id token cookie by reading the response got from backend.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s …
=> Bug fix and minor code formatting

components/dashboards-web-component/src/viewer/DashboardViewPage.jsx, components/dashboards-web-component/src/viewer/components/dashboard-container-styles.css
Enable scroll for lower resolutions
Fixes: https://github.com/wso2/analytics-apim/issues/865 
> Link to the PR for changes to the …
=> Enable scroll for lower resolutions

components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/authorizer/DashboardAuthorizerServiceStub.java
This PR updates the admin rest api version from v15.0 to v16.0 …
=> Update the admin rest api version

components/dashboards-web-component/src/designer/components/WidgetCard.jsx
Fix widget panel visibility in dashboard designer
Fixes https://github.com/wso2/analytics-apim/issues/668
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification …
=> Fix widget panel visibility in dashboard designer

components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/database/QueryManager.java
Add case sensitivity check
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …
=> Add case sensitivity check

components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/database/QueryManager.java
Fix use of non-localized String.toLowerCase() issue …
=> Fix use of non-localized String.toLowerCase() issue

components/dashboards-web-component/src/viewer/components/side-bar-nav-styles.css
Fixes https://github.com/wso2/analytics-apim/issues/760 …
=> Fix Left side tabs visibility

components/dashboards-web-component/src/common/Header.jsx, components/dashboards/org.wso2.carbon.dashboards.api/src/main/java/org/wso2/carbon/dashboards/api/internal/DashboardRestApi.java, components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/DashboardMetadataProvider.java, components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/DashboardThemeConfigProvider.java, components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/DefaultDashboardThemeConfigProvider.java, components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/bean/DashboardConfigurations.java, components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/DashboardMetadataProviderImpl.java, components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/StartupListener.java, components/dashboards/org.wso2.carbon.dashboards.core/src/test/java/org/wso2/carbon/dashboards/core/internal/DashboardMetadataProviderImplTest.java
Add ability to add a custom logo for the analytics-dashboard …
=> Adding capability to add a custom logo

pom.xml
This PR updates dependency versions and plugins. …
=> Dependency updates and plugin updates

components/dashboards/org.wso2.carbon.dashboards.core/src/test/java/org/wso2/carbon/dashboards/core/internal/DashboardMetadataProviderImplTest.java
Update test case
https://github.com/wso2/carbon-dashboards/pull/1215
=> Update test case

components/dashboards-web-component/src/listing/DashboardListingPage.jsx, components/dashboards-web-component/src/listing/components/DashboardCard.jsx, components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/DashboardMetadataProviderImpl.java
Fixed https://github.com/wso2/analytics-apim/issues/1034
=> Fixed https://github.com/wso2/analytics-apim/issues/1034

components/dashboards-web-component/src/utils/apis/DashboardAPI.jsx
Fixed https://github.com/wso2/analytics-apim/issues/1056
=> Fxied https://github.com/wso2/analytics-apim/issues/1056

components/dashboards-web-component/package-lock.json, components/dashboards-web-component/package.json
Update react to 16.13.1
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …
=> Update react to 16.13.1

components/dashboards-web-component/src/auth/Login.jsx
Partial fix for the issue #1221, this will allow automation scripts to be made for login portal
=> Add id to ui elements in login portal

components/dashboards-web-component/src/auth/Login.jsx, components/dashboards-web-component/src/utils/WidgetChannelManager.js
Resolves wso2/carbon-dashboards#1226 and resolves wso2/carbon-dashboards#1227
Fix provided by @lasanthaS.
N/A
N/A as this is a bug fix.
N/A as this is a bug fix.
Google Chrome Version 81.0.4044.129 (Official Build) (64-bit)
Mac OS 10.13.1 (17B1003)
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
=> Fix wso2/carbon-dashboards#1226 and wso2/carbon-dashboards#1227

base-widget/src/Widget.jsx
Fixes  https://github.com/wso2/analytics-apim/issues/1140
Tested modified widgets in local setup.
npm 6.14.5
node v14.2.0
Firefox 72.0.2
Chrome 81.0.4044.138
=> Replaces hash based widget state passing with query parameter.

base-widget/package.json
=> Bump base widget version in order to release base-widget@1.5.0

components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/DashboardMetadataProvider.java, components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/DashboardMetadataProviderImpl.java, components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/database/DashboardMetadataDao.java
=> Fixed dashboard loading order

components/dashboards-web-component/src/designer/components/WidgetsSidePane.jsx
Fix widget list not loading issue
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, …
=> Fix widget list not loading issue

components/dashboards/org.wso2.carbon.dashboards.core/src/test/java/org/wso2/carbon/dashboards/core/internal/DashboardMetadataProviderImplTest.java
=> Fixed test failure

components/dashboards/org.wso2.carbon.dashboards.api/src/main/java/org/wso2/carbon/dashboards/api/internal/DashboardRestApi.java, components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/internal/DashboardMetadataProviderImpl.java
This PR fixes issues reported after the PR analysis of the following PRs:
https://github.com/wso2/carbon-dashboards/pull/1193
=> Fix PR review commnets

features/org.wso2.carbon.dashboards.api.feature/pom.xml, pom.xml
=> Update h2 version

components/dashboards-web-component/src/designer/DashboardSettingsPage.jsx
Fixed https://github.com/wso2/analytics-apim/issues/1426
URL, Name, and Description are disabled to edit when the dashboard is read-only. Update rest API request also skips for such dashboards. 
If someone wants to change this information, need to update the related dashboards JSON in the file system. If it is already persisted in the DB, need to delete and restart the server to redeploy.
=> Disabled dashboard update when it is readonly. 

components/dashboards-web-component/src/auth/Login.jsx, components/dashboards-web-component/src/utils/WidgetChannelManager.js, components/dashboards/org.wso2.carbon.dashboards.core/src/main/java/org/wso2/carbon/dashboards/core/bean/DashboardConfigurations.java
Resolves https://github.com/wso2/analytics-apim/issues/1438
=> Fix for analytics-apim#1438

components/dashboards-web-component/src/gadgets-generation-wizard/components/GadgetsGenerationWizard.jsx
This PR fixes an issue in the WebSocket data provider while creating a widget via the Widget generation wizard.
=> Fix an issue in the WebSocket data provider

base-widget/package-lock.json, components/dashboards-web-component/package-lock.json, components/universal-widget/package-lock.json
Related to https://github.com/wso2/analytics-apim/issues/1413
Bump @wso2-dashboards/widget version to 1.5.1 in package-lock.json files
=> Bump @wso2-dashboards/widget version to 1.5.1 in package-lock.json files

base-widget/package.json, components/dashboards-web-component/package.json, components/universal-widget/package.json, samples/widgets/Publisher/package.json, samples/widgets/UserInfo/package.json, samples/widgets/WidgetState/package.json, samples/widgets/sales-dashboard-widgets/CustomersByProduct/package.json, samples/widgets/sales-dashboard-widgets/CustomersPerYear/package.json, samples/widgets/sales-dashboard-widgets/OverallProductInfo/package.json, samples/widgets/sales-dashboard-widgets/OverallRevenueInfo/package.json, samples/widgets/sales-dashboard-widgets/RevenueByCountry/package.json, samples/widgets/sales-dashboard-widgets/RevenueByProduct/package.json, samples/widgets/sales-dashboard-widgets/RevenueByProductWithUserPreferences/package.json, samples/widgets/sales-dashboard-widgets/RevenueByRegion/package.json, samples/widgets/sales-dashboard-widgets/RevenuePerYear/package.json, samples/widgets/sales-dashboard-widgets/RevenuePercentage/package.json
Updates version to the latest 1.5.0
=> Bump dependency version - @wso2-dashboards/Widgets.
